return {
	{ "a01_N_Zentai_010",	 { "Other" },		"World" },
	{ "a01_N_Skeleton_010", { "Other" },		"Skeleton" },

	{ "a01_J_Neck_01",		 { "Torso" },		"Neck 1" },
	{ "a01_J_Neck_02",		 { "Torso" },		"Neck 2" },
	{ "a01_J_Neck_03",		 { "Torso" },		"Neck 3" },
	{ "a01_J_Hip_010",		 { "Torso" },		"Center" },
	{ "a01_J_Spin_010",		 { "Torso" },		"Waist" },
	{ "a01_J_Spin_020",		 { "Torso" },		"Chest" },
	{ "a01_J_Kosi_010",		 { "Torso" },		"Hip" },
	{ "a01_J_KataL_01",		 { "Torso" },		"Left Shoulder" },
	{ "a01_J_KataR_01",		 { "Torso" },		"Right Shoulder" },

	{ "a01_J_ArmL_00",		 { "Left Arm" },		"Left Anchor" },
	{ "a01_J_ArmL_01",		 { "Left Arm" },		"Left Arm" },
	{ "a01_J_ArmL_02",		 { "Left Arm" },		"Left Shoulder" },
	{ "a01_J_UdeL_01",		 { "Left Arm" },		"Left Underarm " },
	{ "a01_J_HijiL_01",		 { "Left Arm" },		"Left Elbow" },

	{ "a01_J_ArmR_00",		 { "Right Arm" },		"Anchor" },
	{ "a01_J_ArmR_01",		 { "Right Arm" },		"Arm" },
	{ "a01_J_ArmR_02",		 { "Right Arm" },		"Shoulder" },
	{ "a01_J_UdeR_01",		 { "Right Arm" },		"Underarm " },
	{ "a01_J_HijiR_01",		 { "Right Arm" },		"Elbow" },
	
	{ "a01_J_HandL_01",		 { "Left Arm", "Left Hand" },		"Left Hand" },
	{ "a01_J_HandL_02",		 { "Left Hand" },		"Left Hand 2" },
	{ "a01_J_HitoL_01",		 { "Left Hand" },		"Left Index Finger 1" },
	{ "a01_J_HitoL_02",		 { "Left Hand" },		"Left Index Finger 2" },
	{ "a01_J_HitoL_03",		 { "Left Hand" },		"Left Index Finger 3" },
	{ "a01_J_NakaL_01",		 { "Left Hand" },		"Left Middle Finger 1" },
	{ "a01_J_NakaL_02",		 { "Left Hand" },		"Left Middle Finger 2" },
	{ "a01_J_NakaL_03",		 { "Left Hand" },		"Left Middle Finger 3" },
	{ "a01_J_KusuriL_01",	 { "Left Hand" },		"Left Ring Finger 1" },
	{ "a01_J_KusuriL_02",	 { "Left Hand" },		"Left Ring Finger 2" },
	{ "a01_J_KusuriL_03",	 { "Left Hand" },		"Left Ring Finger 3" },
	{ "a01_J_KoL_01",			 { "Left Hand" },		"Left Little Finger 1" },
	{ "a01_J_KoL_02",			 { "Left Hand" },		"Left Little Finger 2" },
	{ "a01_J_KoL_03",			 { "Left Hand" },		"Left Little Finger 3" },
	{ "a01_J_OyaL_01",		 { "Left Hand" },		"Left Thumb 1" },
	{ "a01_J_OyaL_02",		 { "Left Hand" },		"Left Thumb 2" },
	{ "a01_J_OyaL_03",		 { "Left Hand" },		"Left Thumb 3" },

	{ "a01_J_HandR_01",		 { "Right Arm", "Right Hand" },		"Hand" },
	{ "a01_J_HandR_02",		 { "Right Hand" },		"Hand 2" },
	{ "a01_J_HitoR_01",		 { "Right Hand" },		"Index Finger 1" },
	{ "a01_J_HitoR_02",		 { "Right Hand" },		"Index Finger 2" },
	{ "a01_J_HitoR_03",		 { "Right Hand" },		"Index Finger 3" },
	{ "a01_J_NakaR_01",		 { "Right Hand" },		"Middle Finger 1" },
	{ "a01_J_NakaR_02",		 { "Right Hand" },		"Middle Finger 2" },
	{ "a01_J_NakaR_03",		 { "Right Hand" },		"Middle Finger 3" },
	{ "a01_J_KusuriR_01",	 { "Right Hand" },		"Ring Finger 1" },
	{ "a01_J_KusuriR_02",	 { "Right Hand" },		"Ring Finger 2" },
	{ "a01_J_KusuriR_03",	 { "Right Hand" },		"Ring Finger 3" },
	{ "a01_J_KoR_01",			 { "Right Hand" },		"Little Finger 1" },
	{ "a01_J_KoR_02",			 { "Right Hand" },		"Little Finger 2" },
	{ "a01_J_KoR_03",			 { "Right Hand" },		"Little Finger 3" },
	{ "a01_J_OyaR_01",		 { "Right Hand" },		"Thumb 1" },
	{ "a01_J_OyaR_02",		 { "Right Hand" },		"Thumb 2" },
	{ "a01_J_OyaR_03",		 { "Right Hand" },		"Thumb 3" },

	{ "a01_J_UplegL_010",	 { "Left Leg" },		"Left Upper Leg" },
	{ "a01_J_LegL_01",		 { "Left Leg" },		"Left Lower Leg" },
	{ "a01_J_HizaL_01",		 { "Left Leg" },		"Left Knee" },
	{ "a01_J_FootL_02",		 { "Left Leg" },		"Left Foot 1" },
	{ "a01_J_FootL_03",		 { "Left Leg" },		"Left Foot 2" },
	{ "a01_J_ToesL_01",		 { "Left Leg" },		"Left Toes" },

	{ "a01_J_UplegR_010",	 { "Right Leg" },		"Right Upper Leg" },
	{ "a01_J_LegR_01",		 { "Right Leg" },		"Right Lower Leg" },
	{ "a01_J_HizaR_01",		 { "Right Leg" },		"Right Knee" },
	{ "a01_J_FootR_02",		 { "Right Leg" },		"Right Foot 1" },
	{ "a01_J_FootR_03",		 { "Right Leg" },		"Right Foot 2" },
	{ "a01_J_ToesR_01",		 { "Right Leg" },		"Right Toes" },

	{ "a01_J_MuneR_01",		 { "Breasts" },	"Right Breast 1" },
	{ "a01_J_MuneR_02",		 { "Breasts" },	"Right Breast 2" },
	{ "a01_J_MuneL_01",		 { "Breasts" },	"Left Breast 1" },
	{ "a01_J_MuneL_02",		 { "Breasts" },	"Left Breast 2" },

	{ "a_J_dan00",				 { "Other" },		"a_J_dan00" },
	{ "a_J_dan01",				 { "Other" },		"a_J_dan01" },
	{ "a_J_dan02",				 { "Other" },		"a_J_dan02" },
	{ "a_J_dan03",				 { "Other" },		"a_J_dan03" },
	{ "a_J_dan04",				 { "Other" },		"a_J_dan04" },
	{ "a_J_dan05",				 { "Other" },		"a_J_dan05" },
	{ "a_J_dan06",				 { "Other" },		"a_J_dan06" },
	{ "a_J_dan07",				 { "Other" },		"a_J_dan07" },
	{ "a_J_dan08",				 { "Other" },		"a_J_dan08" },
	{ "a_J_dan09",				 { "Other" },		"a_J_dan09" },
	{ "a01_J_NikuL_00",		 { "Other" },		"Left Vagina Lip" },
	{ "a01_J_NikuR_00",		 { "Other" },		"Right Vagina Lip" },

	{ "A00_N_hitomiL",		 { "Face" },		"Left Iris" },
	{ "A00_N_hitomiR",		 { "Face" },		"Right Iris" },
	{ "A00_J_mayuLrot",		 { "Face" },		"Left Eyebrow" },
	{ "A00_J_mayuRrot",		 { "Face" },		"Right Eyebrow" },
	{ "AS00_N_megane",		 { "Face" },		"Glasses" },
	{ "A00_J_kuti",				 { "Face" },		"Mouth" },
	{ "A00_J_sita00",			 { "Face" },		"Tongue 1" },
	{ "A00_J_sita01",			 { "Face" },		"Tongue 2" },
	{ "A00_J_sita02",			 { "Face" },		"Tongue 3" },
	{ "A00_J_sita03",			 { "Face" },		"Tongue 4" },
	{ "A00_J_sita04",			 { "Face" },		"Tongue 5" },
	{ "A00_J_sita05",			 { "Face" },		"Tongue 6" },
	{ "A00_J_sita06",			 { "Face" },		"Tongue 7" },
	{ "A00_O_namida",		 { "Face" },		"Tears" },
	
	{ "a01_J_SK_F_01",		 { "Skirt" },		"SK_F_01" },
	{ "a01_J_SK_F_02",		 { "Skirt" },		"SK_F_02" },
	{ "a01_J_SK_F_03",		 { "Skirt" },		"SK_F_03" },
	{ "a01_J_SK_F_04",		 { "Skirt" },		"SK_F_04" },
	{ "a01_J_SK_FR_01",		 { "Skirt" },		"SK_FR_01" },
	{ "a01_J_SK_FR_02",		 { "Skirt" },		"SK_FR_02" },
	{ "a01_J_SK_FR_03",		 { "Skirt" },		"SK_FR_03" },
	{ "a01_J_SK_FR_04",		 { "Skirt" },		"SK_FR_04" },
	{ "a01_J_SK_FL_01",		 { "Skirt" },		"SK_FL_01" },
	{ "a01_J_SK_FL_02",		 { "Skirt" },		"SK_FL_02" },
	{ "a01_J_SK_FL_03",		 { "Skirt" },		"SK_FL_03" },
	{ "a01_J_SK_FL_04",		 { "Skirt" },		"SK_FL_04" },
	{ "a01_J_SK_SR_01",		 { "Skirt" },		"SK_SR_01" },
	{ "a01_J_SK_SR_02",		 { "Skirt" },		"SK_SR_02" },
	{ "a01_J_SK_SR_03",		 { "Skirt" },		"SK_SR_03" },
	{ "a01_J_SK_SR_04",		 { "Skirt" },		"SK_SR_04" },
	{ "a01_J_SK_SL_01",		 { "Skirt" },		"SK_SL_01" },
	{ "a01_J_SK_SL_02",		 { "Skirt" },		"SK_SL_02" },
	{ "a01_J_SK_SL_03",		 { "Skirt" },		"SK_SL_03" },
	{ "a01_J_SK_SL_04",		 { "Skirt" },		"SK_SL_04" },
	{ "a01_J_SK_U_01",		 { "Skirt" },		"SK_U_01" },
	{ "a01_J_SK_U_02",		 { "Skirt" },		"SK_U_02" },
	{ "a01_J_SK_U_03",		 { "Skirt" },		"SK_U_03" },
	{ "a01_J_SK_U_04",		 { "Skirt" },		"SK_U_04" },
	{ "a01_J_SK_UR_01",		 { "Skirt" },		"SK_UR_01" },
	{ "a01_J_SK_UR_02",		 { "Skirt" },		"SK_UR_02" },
	{ "a01_J_SK_UR_03",		 { "Skirt" },		"SK_UR_03" },
	{ "a01_J_SK_UR_04",		 { "Skirt" },		"SK_UR_04" },
	{ "a01_J_SK_UL_01",		 { "Skirt" },		"SK_UL_01" },
	{ "a01_J_SK_UL_02",		 { "Skirt" },		"SK_UL_02" },
	{ "a01_J_SK_UL_03",		 { "Skirt" },		"SK_UL_03" },
	{ "a01_J_SK_UL_04",		 { "Skirt" },		"SK_UL_04" },
}
