-- Notes:
-- Friendly names must be unique
-- Bones are shown in the poser as ordered here
return {
	{ "a01_N_Zentai_010",	 { "Torso" },		"World" },
	{ "a01_N_Skeleton_010",	 { "Torso" },		"Skeleton" },
	{ "a01_J_Spin_021",		 { "Torso" },		"Neck Base" },
	{ "a01_J_Neck_01",		 { "Torso" },		"Neck 1" },
	{ "a01_J_Neck_02",		 { "Torso" },		"Neck 2" },
	{ "a01_J_Neck_03",		 { "Torso" },		"Head Pivot" },
	{ "a01_J_Hip_010",		 { "Torso" },		"Center" },
	{ "a01_J_Spin_020",		 { "Torso" },		"Chest" },
	{ "a01_J_Spin_010",		 { "Torso" },		"Waist" },
	{ "a01_J_Kosi_010",		 { "Torso" },		"Hip" },
	{ "a01_J_Kosi_020",		 { "Torso" },		"Hip Bottom" },
	{ "a01_J_SiriL_010",		 { "Torso" },		"Ass Cheek Left" },
	{ "a01_J_SiriR_010",		 { "Torso" },		"Ass Cheek Right" },
	{ "a01_J_NikuL_00",		 { "Torso" },		"Left Vagina Lip" },
	{ "a01_J_NikuR_00",		 { "Torso" },		"Right Vagina Lip" },
	{ "a_J_dan00",				 { "Torso" },		"Strapon0" },
	{ "a_J_dan01",				 { "Torso" },		"Strapon1" },
	{ "a_J_dan02",				 { "Torso" },		"Strapon2" },
	{ "a_J_dan03",				 { "Torso" },		"Strapon3" },
	{ "a_J_dan04",				 { "Torso" },		"Strapon4" },
	{ "a_J_dan05",				 { "Torso" },		"Strapon5" },
	{ "a_J_dan06",				 { "Torso" },		"Strapon6" },
	{ "a_J_dan07",				 { "Torso" },		"Strapon7" },
	{ "a_J_dan08",				 { "Torso" },		"Strapon8" },
	{ "a_J_dan09",				 { "Torso" },		"Strapon9" },

	{ "a01_J_ArmL_00",		 { "Left Arm" },		"1st Left Arm Anchor" },
	{ "a01_J_ArmL_02",		 { "Left Arm" },		"1st Left Arm Pit" },
	{ "a01_J_ArmL_01",		 { "Left Arm" },		"1st Left Arm" },
	{ "a01_J_KataL_01",		 { "Left Arm" },		"1st Left Shoulder 1" },
	{ "a01_J_KataL_02",		 { "Left Arm" },		"1st Left Shoulder 2" },
	{ "a01_J_UdeL_01",		 { "Left Arm" },		"1st Left Underarm " },
	{ "a01_J_UdeL_02",		 { "Left Arm" },		"1st Left Underarm 2" },
	{ "a01_J_HijiL_01",		 { "Left Arm" },		"1st Left Elbow" },
	{ "a01_J_TekubiL_01",	 { "Left Arm" },		"1st Left Wrist" },

	{ "a01_J_ArmR_00",		 { "Right Arm" },		"1st Right Arm Anchor" },
	{ "a01_J_ArmR_02",		 { "Right Arm" },		"1st Right Arm Pit" },
	{ "a01_J_ArmR_01",		 { "Right Arm" },		"1st Right Arm" },
	{ "a01_J_KataR_01",		 { "Right Arm" },		"1st Right Shoulder 1" },
	{ "a01_J_KataR_02",		 { "Right Arm" },		"1st Right Shoulder 2" },
	{ "a01_J_UdeR_01",		 { "Right Arm" },		"1st Right Underarm " },
	{ "a01_J_UdeR_02",		 { "Right Arm" },		"1st Right Underarm 2" },
	{ "a01_J_HijiR_01",		 { "Right Arm" },		"1st Right Elbow" },
	{ "a01_J_TekubiR_01",	 { "Right Arm" },		"1st Right Wrist" },
	
	{ "a01_J_HandL_01",		 { "Left Arm", "Left Hand" },		"1st Left Hand" },
	{ "a01_J_HandL_02",		 { "Left Hand" },		"1st Left Hand 2" },
	{ "a01_J_HitoL_01",		 { "Left Hand" },		"1st Left Index Finger 1" },
	{ "a01_J_HitoL_02",		 { "Left Hand" },		"1st Left Index Finger 2" },
	{ "a01_J_HitoL_03",		 { "Left Hand" },		"1st Left Index Finger 3" },
	{ "a01_J_NakaL_01",		 { "Left Hand" },		"1st Left Middle Finger 1" },
	{ "a01_J_NakaL_02",		 { "Left Hand" },		"1st Left Middle Finger 2" },
	{ "a01_J_NakaL_03",		 { "Left Hand" },		"1st Left Middle Finger 3" },
	{ "a01_J_KusuriL_01",	 { "Left Hand" },		"1st Left Ring Finger 1" },
	{ "a01_J_KusuriL_02",	 { "Left Hand" },		"1st Left Ring Finger 2" },
	{ "a01_J_KusuriL_03",	 { "Left Hand" },		"1st Left Ring Finger 3" },
	{ "a01_J_KoL_01",			 { "Left Hand" },		"1st Left Little Finger 1" },
	{ "a01_J_KoL_02",			 { "Left Hand" },		"1st Left Little Finger 2" },
	{ "a01_J_KoL_03",			 { "Left Hand" },		"1st Left Little Finger 3" },
	{ "a01_J_OyaL_01",		 { "Left Hand" },		"1st Left Thumb 1" },
	{ "a01_J_OyaL_02",		 { "Left Hand" },		"1st Left Thumb 2" },
	{ "a01_J_OyaL_03",		 { "Left Hand" },		"1st Left Thumb 3" },

	{ "a01_J_HandR_01",		 { "Right Arm", "Right Hand" },		"1st Right Hand" },
	{ "a01_J_HandR_02",		 { "Right Hand" },		"1st Right Hand 2" },
	{ "a01_J_HitoR_01",		 { "Right Hand" },		"1st Right Index Finger 1" },
	{ "a01_J_HitoR_02",		 { "Right Hand" },		"1st Right Index Finger 2" },
	{ "a01_J_HitoR_03",		 { "Right Hand" },		"1st Right Index Finger 3" },
	{ "a01_J_NakaR_01",		 { "Right Hand" },		"1st Right Middle Finger 1" },
	{ "a01_J_NakaR_02",		 { "Right Hand" },		"1st Right Middle Finger 2" },
	{ "a01_J_NakaR_03",		 { "Right Hand" },		"1st Right Middle Finger 3" },
	{ "a01_J_KusuriR_01",	 { "Right Hand" },		"1st Right Ring Finger 1" },
	{ "a01_J_KusuriR_02",	 { "Right Hand" },		"1st Right Ring Finger 2" },
	{ "a01_J_KusuriR_03",	 { "Right Hand" },		"1st Right Ring Finger 3" },
	{ "a01_J_KoR_01",			 { "Right Hand" },		"1st Right Little Finger 1" },
	{ "a01_J_KoR_02",			 { "Right Hand" },		"1st Right Little Finger 2" },
	{ "a01_J_KoR_03",			 { "Right Hand" },		"1st Right Little Finger 3" },
	{ "a01_J_OyaR_01",		 { "Right Hand" },		"1st Right Thumb 1" },
	{ "a01_J_OyaR_02",		 { "Right Hand" },		"1st Right Thumb 2" },
	{ "a01_J_OyaR_03",		 { "Right Hand" },		"1st Right Thumb 3" },

	{ "a01_J_UplegL_010",	 { "Left Leg" },		"Left Upper Leg 1" },
	{ "a01_J_UplegL_020",	 { "Left Leg" },		"Left Upper Leg 2" },
	{ "a01_J_UplegDDL_010",	 { "Left Leg" },		"Left Upper Leg 3" },
	{ "a01_J_UplegDDL_020",	 { "Left Leg" },		"Left Upper Leg 4" },
	{ "a01_J_LegL_01",		 { "Left Leg" },		"Left Lower Leg" },
	{ "a01_J_HizaL_01",		 { "Left Leg" },		"Left Knee" },
	{ "a01_J_FootL_02",		 { "Left Leg" },		"Left Foot 1" },
	{ "a01_J_FootL_03",		 { "Left Leg" },		"Left Foot 2" },
	{ "a01_J_ToesL_01",		 { "Left Leg" },		"Left Toes" },
	{ "a01_J_BigToeL",		 { "Left Leg" },		"Left Toe 1" },
	{ "a01_J_Toe2L",		 { "Left Leg" },		"Left Toe 2" },
	{ "a01_J_Toe3L",		 { "Left Leg" },		"Left Toe 3" },
	{ "a01_J_Toe4L",		 { "Left Leg" },		"Left Toe 4" },
	{ "a01_J_Toe5L",		 { "Left Leg" },		"Left Toe 5" },

	{ "a01_J_UplegR_010",	 { "Right Leg" },		"Right Upper Leg 1" },
	{ "a01_J_UplegR_020",	 { "Right Leg" },		"Right Upper Leg 2" },
	{ "a01_J_UplegDDR_010",	 { "Right Leg" },		"Right Upper Leg 3" },
	{ "a01_J_UplegDDR_020",	 { "Right Leg" },		"Right Upper Leg 4" },
	{ "a01_J_LegR_01",		 { "Right Leg" },		"Right Lower Leg" },
	{ "a01_J_HizaR_01",		 { "Right Leg" },		"Right Knee" },
	{ "a01_J_FootR_02",		 { "Right Leg" },		"Right Foot 1" },
	{ "a01_J_FootR_03",		 { "Right Leg" },		"Right Foot 2" },
	{ "a01_J_ToesR_01",		 { "Right Leg" },		"Right Toes" },
	{ "a01_J_BigToeR",		 { "Right Leg" },		"Right Toe 1" },
	{ "a01_J_Toe2R",		 { "Right Leg" },		"Right Toe 2" },
	{ "a01_J_Toe3R",		 { "Right Leg" },		"Right Toe 3" },
	{ "a01_J_Toe4R",		 { "Right Leg" },		"Right Toe 4" },
	{ "a01_J_Toe5R",		 { "Right Leg" },		"Right Toe 5" },
-- these are the extra arms bones (second)
	{ "a01_J_ArmL_00_second",		 { "Left Arm" },		"2nd Left Arm Anchor" },
	{ "a01_J_ArmL_02_second",		 { "Left Arm" },		"2nd Left Arm Pit" },
	{ "a01_J_ArmL_01_second",		 { "Left Arm" },		"2nd Left Arm" },
	{ "a01_J_KataL_01_second",		 { "Left Arm" },		"2nd Left Shoulder 1" },
	{ "a01_J_KataL_02_second",		 { "Left Arm" },		"2nd Left Shoulder 2" },
	{ "a01_J_UdeL_01_second",		 { "Left Arm" },		"2nd Left Underarm " },
	{ "a01_J_UdeL_02_second",		 { "Left Arm" },		"2nd Left Underarm 2" },
	{ "a01_J_HijiL_01_second",		 { "Left Arm" },		"2nd Left Elbow" },
	{ "a01_J_TekubiL_01_second",	 { "Left Arm" },		"2nd Left Wrist" },

	{ "a01_J_ArmR_00_second",		 { "Right Arm" },		"2nd Right Arm Anchor" },
	{ "a01_J_ArmR_02_second",		 { "Right Arm" },		"2nd Right Arm Pit" },
	{ "a01_J_ArmR_01_second",		 { "Right Arm" },		"2nd Right Arm" },
	{ "a01_J_KataR_01_second",		 { "Right Arm" },		"2nd Right Shoulder 1" },
	{ "a01_J_KataR_02_second",		 { "Right Arm" },		"2nd Right Shoulder 2" },
	{ "a01_J_UdeR_01_second",		 { "Right Arm" },		"2nd Right Underarm " },
	{ "a01_J_UdeR_02_second",		 { "Right Arm" },		"2nd Right Underarm 2" },
	{ "a01_J_HijiR_01_second",		 { "Right Arm" },		"2nd Right Elbow" },
	{ "a01_J_TekubiR_01_second",	 { "Right Arm" },		"2nd Right Wrist" },
	
	{ "a01_J_HandL_01_second",		 { "Left Arm", "Left Hand" },		"2nd Left Hand" },
	{ "a01_J_HandL_02_second",		 { "Left Hand" },		"2nd Left Hand 2" },
	{ "a01_J_HitoL_01_second",		 { "Left Hand" },		"2nd Left Index Finger 1" },
	{ "a01_J_HitoL_02_second",		 { "Left Hand" },		"2nd Left Index Finger 2" },
	{ "a01_J_HitoL_03_second",		 { "Left Hand" },		"2nd Left Index Finger 3" },
	{ "a01_J_NakaL_01_second",		 { "Left Hand" },		"2nd Left Middle Finger 1" },
	{ "a01_J_NakaL_02_second",		 { "Left Hand" },		"2nd Left Middle Finger 2" },
	{ "a01_J_NakaL_03_second",		 { "Left Hand" },		"2nd Left Middle Finger 3" },
	{ "a01_J_KusuriL_01_second",	 { "Left Hand" },		"2nd Left Ring Finger 1" },
	{ "a01_J_KusuriL_02_second",	 { "Left Hand" },		"2nd Left Ring Finger 2" },
	{ "a01_J_KusuriL_03_second",	 { "Left Hand" },		"2nd Left Ring Finger 3" },
	{ "a01_J_KoL_01_second",			 { "Left Hand" },		"2nd Left Little Finger 1" },
	{ "a01_J_KoL_02_second",			 { "Left Hand" },		"2nd Left Little Finger 2" },
	{ "a01_J_KoL_03_second",			 { "Left Hand" },		"2nd Left Little Finger 3" },
	{ "a01_J_OyaL_01_second",		 { "Left Hand" },		"2nd Left Thumb 1" },
	{ "a01_J_OyaL_02_second",		 { "Left Hand" },		"2nd Left Thumb 2" },
	{ "a01_J_OyaL_03_second",		 { "Left Hand" },		"2nd Left Thumb 3" },

	{ "a01_J_HandR_01_second",		 { "Right Arm", "Right Hand" },		"2nd Right Hand" },
	{ "a01_J_HandR_02_second",		 { "Right Hand" },		"2nd Right Hand 2" },
	{ "a01_J_HitoR_01_second",		 { "Right Hand" },		"2nd Right Index Finger 1" },
	{ "a01_J_HitoR_02_second",		 { "Right Hand" },		"2nd Right Index Finger 2" },
	{ "a01_J_HitoR_03_second",		 { "Right Hand" },		"2nd Right Index Finger 3" },
	{ "a01_J_NakaR_01_second",		 { "Right Hand" },		"2nd Right Middle Finger 1" },
	{ "a01_J_NakaR_02_second",		 { "Right Hand" },		"2nd Right Middle Finger 2" },
	{ "a01_J_NakaR_03_second",		 { "Right Hand" },		"2nd Right Middle Finger 3" },
	{ "a01_J_KusuriR_01_second",	 { "Right Hand" },		"2nd Right Ring Finger 1" },
	{ "a01_J_KusuriR_02_second",	 { "Right Hand" },		"2nd Right Ring Finger 2" },
	{ "a01_J_KusuriR_03_second",	 { "Right Hand" },		"2nd Right Ring Finger 3" },
	{ "a01_J_KoR_01_second",			 { "Right Hand" },		"2nd Right Little Finger 1" },
	{ "a01_J_KoR_02_second",			 { "Right Hand" },		"2nd Right Little Finger 2" },
	{ "a01_J_KoR_03_second",			 { "Right Hand" },		"2nd Right Little Finger 3" },
	{ "a01_J_OyaR_01_second",		 { "Right Hand" },		"2nd Right Thumb 1" },
	{ "a01_J_OyaR_02_second",		 { "Right Hand" },		"2nd Right Thumb 2" },
	{ "a01_J_OyaR_03_second",		 { "Right Hand" },		"2nd Right Thumb 3" },


-- these are the extra arms bones (third)
	{ "a01_J_ArmL_00_third",		 { "Left Arm" },		"3rd Left Arm Anchor" },
	{ "a01_J_ArmL_02_third",		 { "Left Arm" },		"3rd Left Arm Pit" },
	{ "a01_J_ArmL_01_third",		 { "Left Arm" },		"3rd Left Arm" },
	{ "a01_J_KataL_01_third",		 { "Left Arm" },		"3rd Left Shoulder 1" },
	{ "a01_J_KataL_02_third",		 { "Left Arm" },		"3rd Left Shoulder 2" },
	{ "a01_J_UdeL_01_third",		 { "Left Arm" },		"3rd Left Underarm " },
	{ "a01_J_UdeL_02_third",		 { "Left Arm" },		"3rd Left Underarm 2" },
	{ "a01_J_HijiL_01_third",		 { "Left Arm" },		"3rd Left Elbow" },
	{ "a01_J_TekubiL_01_third",	 { "Left Arm" },		"3rd Left Wrist" },

	{ "a01_J_ArmR_00_third",		 { "Right Arm" },		"3rd Right Arm Anchor" },
	{ "a01_J_ArmR_02_third",		 { "Right Arm" },		"3rd Right Arm Pit" },
	{ "a01_J_ArmR_01_third",		 { "Right Arm" },		"3rd Right Arm" },
	{ "a01_J_KataR_01_third",		 { "Right Arm" },		"3rd Right Shoulder 1" },
	{ "a01_J_KataR_02_third",		 { "Right Arm" },		"3rd Right Shoulder 2" },
	{ "a01_J_UdeR_01_third",		 { "Right Arm" },		"3rd Right Underarm " },
	{ "a01_J_UdeR_02_third",		 { "Right Arm" },		"3rd Right Underarm 2" },
	{ "a01_J_HijiR_01_third",		 { "Right Arm" },		"3rd Right Elbow" },
	{ "a01_J_TekubiR_01_third",	 { "Right Arm" },		"3rd Right Wrist" },
	
	{ "a01_J_HandL_01_third",		 { "Left Arm", "Left Hand" },		"3rd Left Hand" },
	{ "a01_J_HandL_02_third",		 { "Left Hand" },		"3rd Left Hand 2" },
	{ "a01_J_HitoL_01_third",		 { "Left Hand" },		"3rd Left Index Finger 1" },
	{ "a01_J_HitoL_02_third",		 { "Left Hand" },		"3rd Left Index Finger 2" },
	{ "a01_J_HitoL_03_third",		 { "Left Hand" },		"3rd Left Index Finger 3" },
	{ "a01_J_NakaL_01_third",		 { "Left Hand" },		"3rd Left Middle Finger 1" },
	{ "a01_J_NakaL_02_third",		 { "Left Hand" },		"3rd Left Middle Finger 2" },
	{ "a01_J_NakaL_03_third",		 { "Left Hand" },		"3rd Left Middle Finger 3" },
	{ "a01_J_KusuriL_01_third",	 { "Left Hand" },		"3rd Left Ring Finger 1" },
	{ "a01_J_KusuriL_02_third",	 { "Left Hand" },		"3rd Left Ring Finger 2" },
	{ "a01_J_KusuriL_03_third",	 { "Left Hand" },		"3rd Left Ring Finger 3" },
	{ "a01_J_KoL_01_third",			 { "Left Hand" },		"3rd Left Little Finger 1" },
	{ "a01_J_KoL_02_third",			 { "Left Hand" },		"3rd Left Little Finger 2" },
	{ "a01_J_KoL_03_third",			 { "Left Hand" },		"3rd Left Little Finger 3" },
	{ "a01_J_OyaL_01_third",		 { "Left Hand" },		"3rd Left Thumb 1" },
	{ "a01_J_OyaL_02_third",		 { "Left Hand" },		"3rd Left Thumb 2" },
	{ "a01_J_OyaL_03_third",		 { "Left Hand" },		"3rd Left Thumb 3" },

	{ "a01_J_HandR_01_third",		 { "Right Arm", "Right Hand" },		"3rd Right Hand" },
	{ "a01_J_HandR_02_third",		 { "Right Hand" },		"3rd Right Hand 2" },
	{ "a01_J_HitoR_01_third",		 { "Right Hand" },		"3rd Right Index Finger 1" },
	{ "a01_J_HitoR_02_third",		 { "Right Hand" },		"3rd Right Index Finger 2" },
	{ "a01_J_HitoR_03_third",		 { "Right Hand" },		"3rd Right Index Finger 3" },
	{ "a01_J_NakaR_01_third",		 { "Right Hand" },		"3rd Right Middle Finger 1" },
	{ "a01_J_NakaR_02_third",		 { "Right Hand" },		"3rd Right Middle Finger 2" },
	{ "a01_J_NakaR_03_third",		 { "Right Hand" },		"3rd Right Middle Finger 3" },
	{ "a01_J_KusuriR_01_third",	 { "Right Hand" },		"3rd Right Ring Finger 1" },
	{ "a01_J_KusuriR_02_third",	 { "Right Hand" },		"3rd Right Ring Finger 2" },
	{ "a01_J_KusuriR_03_third",	 { "Right Hand" },		"3rd Right Ring Finger 3" },
	{ "a01_J_KoR_01_third",			 { "Right Hand" },		"3rd Right Little Finger 1" },
	{ "a01_J_KoR_02_third",			 { "Right Hand" },		"3rd Right Little Finger 2" },
	{ "a01_J_KoR_03_third",			 { "Right Hand" },		"3rd Right Little Finger 3" },
	{ "a01_J_OyaR_01_third",		 { "Right Hand" },		"3rd Right Thumb 1" },
	{ "a01_J_OyaR_02_third",		 { "Right Hand" },		"3rd Right Thumb 2" },
	{ "a01_J_OyaR_03_third",		 { "Right Hand" },		"3rd Right Thumb 3" },

	{ "a01_J_MuneR_01",		 { "Breasts" },	"Right Breast 1" },
	{ "a01_J_MuneR_02",		 { "Breasts" },	"Right Breast 2" },
	{ "a01_J_MuneL_01",		 { "Breasts" },	"Left Breast 1" },
	{ "a01_J_MuneL_02",		 { "Breasts" },	"Left Breast 2" },
--	 Leave out until nipples stop glitching
--	{ "a01_J_ChikuR_01",	 { "Breasts" },	"Right Nipple 1" },
--	{ "a01_J_ChikuR_02",	 { "Breasts" },	"Right Nipple 2" },
--	{ "a01_J_ChikuL_01",		 { "Breasts" },	"Left Nipple 1" },
--	{ "a01_J_ChikuL_02",		 { "Breasts" },	"Left Nipple 2" },

	{ "a_J_dan00",				 { "Other" },		"Strapon0" },
	{ "a_J_dan01",				 { "Other" },		"Strapon1" },
	{ "a_J_dan02",				 { "Other" },		"Strapon2" },
	{ "a_J_dan03",				 { "Other" },		"Strapon3" },
	{ "a_J_dan04",				 { "Other" },		"Strapon4" },
	{ "a_J_dan05",				 { "Other" },		"Strapon5" },
	{ "a_J_dan06",				 { "Other" },		"Strapon6" },
	{ "a_J_dan07",				 { "Other" },		"Strapon7" },
	{ "a_J_dan08",				 { "Other" },		"Strapon8" },
	{ "a_J_dan09",				 { "Other" },		"Strapon9" },
	{ "a01_J_NikuL_00",		 { "Other" },		"Left Vagina Lip" },
	{ "a01_J_NikuR_00",		 { "Other" },		"Right Vagina Lip" },
	{ "a01_J_NikuL_01",		 { "Other" },		"Left Ass Meat" },
	{ "a01_J_NikuR_01",		 { "Other" },		"Right Ass Meat" },
	{ "a01_J_SLL_00",		 { "Other" },		"Right Sleeve 0" },
	{ "a01_J_SLL_01",		 { "Other" },		"Right Sleeve 1" },
	{ "a01_J_SLL_02",		 { "Other" },		"Right Sleeve 2" },
	{ "a01_J_SLL_03",		 { "Other" },		"Right Sleeve 3" },
	{ "a01_J_SLL_04",		 { "Other" },		"Right Sleeve 4" },
	{ "a01_J_SLL_05",		 { "Other" },		"Right Sleeve 5" },
	{ "a01_J_SLL_06",		 { "Other" },		"Right Sleeve 6" },
	{ "a01_J_SLR_00",		 { "Other" },		"Left Sleeve 0" },
	{ "a01_J_SLR_01",		 { "Other" },		"Left Sleeve 1" },
	{ "a01_J_SLR_02",		 { "Other" },		"Left Sleeve 2" },
	{ "a01_J_SLR_03",		 { "Other" },		"Left Sleeve 3" },
	{ "a01_J_SLR_04",		 { "Other" },		"Left Sleeve 4" },
	{ "a01_J_SLR_05",		 { "Other" },		"Left Sleeve 5" },
	{ "a01_J_SLR_06",		 { "Other" },		"Left Sleeve 6" },
	
	{ "a01_J_tail00",		 { "Monster-Tail" },		"Tail 0" },
	{ "a01_J_tail01",		 { "Monster-Tail" },		"Tail 1" },
	{ "a01_J_tail02",		 { "Monster-Tail" },		"Tail 2" },
	{ "a01_J_tail03",		 { "Monster-Tail" },		"Tail 3" },
	{ "a01_J_tail04",		 { "Monster-Tail" },		"Tail 4" },
	{ "a01_J_tail05",		 { "Monster-Tail" },		"Tail 5" },
	{ "a01_J_tail06",		 { "Monster-Tail" },		"Tail 6" },
	{ "a01_J_tail07",		 { "Monster-Tail" },		"Tail 7" },
	{ "a01_J_tail08",		 { "Monster-Tail" },		"Tail 8" },
	{ "a01_J_tail09",		 { "Monster-Tail" },		"Tail 9" },
	{ "a01_J_tail10",		 { "Monster-Tail" },		"Tail 10" },
	{ "a01_J_tail11",		 { "Monster-Tail" },		"Tail 11" },
	{ "a01_J_tail12",		 { "Monster-Tail" },		"Tail 12" },
	{ "a01_J_tail13",		 { "Monster-Tail" },		"Tail 13" },
	{ "a01_J_tail14",		 { "Monster-Tail" },		"Tail 14" },
	{ "a01_J_tail15",		 { "Monster-Tail" },		"Tail 15" },
	{ "a01_J_tail16",		 { "Monster-Tail" },		"Tail 16" },
	
	{ "a01_J_Wings_010",		 { "Monster-Wings" },		"Wings Base" },
	{ "a01_J_WingRSpine_01",		 { "Monster-Wings" },		"Right Wing Spine 1" },
	{ "a01_J_WingRSpine_02",		 { "Monster-Wings" },		"Right Wing Spine 2" },
	{ "a01_J_WingRSpine_03",		 { "Monster-Wings" },		"Right Wing Spine 3" },
	{ "a01_J_WingRTalon",		 { "Monster-Wings" },		"Right Wing Talon" },
	{ "a01_J_WingRFold1_01",		 { "Monster-Wings" },		"Right Wing Fold 1-1" },
	{ "a01_J_WingRFold1_02",		 { "Monster-Wings" },		"Right Wing Fold 1-2" },
	{ "a01_J_WingRFold2_01",		 { "Monster-Wings" },		"Right Wing Fold 2-1" },
	{ "a01_J_WingRFold2_02",		 { "Monster-Wings" },		"Right Wing Fold 2-2" },
	{ "a01_J_WingRFold3_01",		 { "Monster-Wings" },		"Right Wing Fold 3-1" },
	{ "a01_J_WingRFold3_02",		 { "Monster-Wings" },		"Right Wing Fold 3-2" },
	{ "a01_J_WingLSpine_01",		 { "Monster-Wings" },		"Left Wing Spine 1" },
	{ "a01_J_WingLSpine_02",		 { "Monster-Wings" },		"Left Wing Spine 2" },
	{ "a01_J_WingLSpine_03",		 { "Monster-Wings" },		"Left Wing Spine 3" },
	{ "a01_J_WingLTalon",		 { "Monster-Wings" },		"Left Wing Talon" },
	{ "a01_J_WingLFold1_01",		 { "Monster-Wings" },		"Left Wing Fold 1-1" },
	{ "a01_J_WingLFold1_02",		 { "Monster-Wings" },		"Left Wing Fold 1-2" },
	{ "a01_J_WingLFold2_01",		 { "Monster-Wings" },		"Left Wing Fold 2-1" },
	{ "a01_J_WingLFold2_02",		 { "Monster-Wings" },		"Left Wing Fold 2-2" },
	{ "a01_J_WingLFold3_01",		 { "Monster-Wings" },		"Left Wing Fold 3-1" },
	{ "a01_J_WingLFold3_02",		 { "Monster-Wings" },		"Left Wing Fold 3-2" },

	{ "A00_N_hitomiL",		 { "Face" },		"Left Iris" },
	{ "A00_N_hitomiR",		 { "Face" },		"Right Iris" },
	{ "S00_N_hitomiL",		 { "Face" },		"Left Iris (M)" },
	{ "S00_N_hitomiR",		 { "Face" },		"Right Iris (M)" },
	{ "A00_J_mayuLrot",		 { "Face" },		"Left Eyebrow" },
	{ "A00_J_mayuRrot",		 { "Face" },		"Right Eyebrow" },
	{ "A00_J_meLTrsX",		 { "Face" },		"Left Eye" },
	{ "A00_J_meRTrsX",		 { "Face" },		"Right Eye" },
	{ "A00_J_meL2",		 { "Face" },		"Left Eye 2" },
	{ "A00_J_meR2",		 { "Face" },		"Right Eye 2" },
	{ "AS00_N_megane",		 { "Face" },		"Glasses" },
	{ "A00_J_kuti",				 { "Face" },		"Mouth" },
	{ "A00_J_sita00",			 { "Face" },		"Tongue 1" },
	{ "A00_J_sita01",			 { "Face" },		"Tongue 2" },
	{ "A00_J_sita02",			 { "Face" },		"Tongue 3" },
	{ "A00_J_sita03",			 { "Face" },		"Tongue 4" },
	{ "A00_J_sita04",			 { "Face" },		"Tongue 5" },
	{ "A00_J_sita05",			 { "Face" },		"Tongue 6" },
	{ "A00_J_sita06",			 { "Face" },		"Tongue 7" },
	{ "A00_J_cheek",			 { "Face" },		"Cheeks" },
	{ "A00_J_nose",			 { "Face" },		"Nose" },
	{ "A00_J_chin",			 { "Face" },		"Chin" },
	{ "A00_J_jaw",			 { "Face" },		"Jaw" },
--	{ "A00_O_namida",		 { "Face" },		"Tears" },
	
	{ "a01_J_SK_F_01",		 { "Skirt" },		"SK_F_01" },
	{ "a01_J_SK_F_02",		 { "Skirt" },		"SK_F_02" },
	{ "a01_J_SK_F_03",		 { "Skirt" },		"SK_F_03" },
	{ "a01_J_SK_F_04",		 { "Skirt" },		"SK_F_04" },
	{ "a01_J_SK_F_05",		 { "Skirt" },		"SK_F_05" },
	{ "a01_J_SK_F_06",		 { "Skirt" },		"SK_F_06" },
	{ "a01_J_SK_FR_01",		 { "Skirt" },		"SK_FR_01" },
	{ "a01_J_SK_FR_02",		 { "Skirt" },		"SK_FR_02" },
	{ "a01_J_SK_FR_03",		 { "Skirt" },		"SK_FR_03" },
	{ "a01_J_SK_FR_04",		 { "Skirt" },		"SK_FR_04" },
	{ "a01_J_SK_FR_05",		 { "Skirt" },		"SK_FR_05" },
	{ "a01_J_SK_FR_06",		 { "Skirt" },		"SK_FR_06" },
	{ "a01_J_SK_FL_01",		 { "Skirt" },		"SK_FL_01" },
	{ "a01_J_SK_FL_02",		 { "Skirt" },		"SK_FL_02" },
	{ "a01_J_SK_FL_03",		 { "Skirt" },		"SK_FL_03" },
	{ "a01_J_SK_FL_04",		 { "Skirt" },		"SK_FL_04" },
	{ "a01_J_SK_FL_05",		 { "Skirt" },		"SK_FL_05" },
	{ "a01_J_SK_FL_06",		 { "Skirt" },		"SK_FL_06" },
	{ "a01_J_SK_SR_01",		 { "Skirt" },		"SK_SR_01" },
	{ "a01_J_SK_SR_02",		 { "Skirt" },		"SK_SR_02" },
	{ "a01_J_SK_SR_03",		 { "Skirt" },		"SK_SR_03" },
	{ "a01_J_SK_SR_04",		 { "Skirt" },		"SK_SR_04" },
	{ "a01_J_SK_SR_05",		 { "Skirt" },		"SK_SR_05" },
	{ "a01_J_SK_SR_06",		 { "Skirt" },		"SK_SR_06" },
	{ "a01_J_SK_SL_01",		 { "Skirt" },		"SK_SL_01" },
	{ "a01_J_SK_SL_02",		 { "Skirt" },		"SK_SL_02" },
	{ "a01_J_SK_SL_03",		 { "Skirt" },		"SK_SL_03" },
	{ "a01_J_SK_SL_04",		 { "Skirt" },		"SK_SL_04" },
	{ "a01_J_SK_SL_05",		 { "Skirt" },		"SK_SL_05" },
	{ "a01_J_SK_SL_06",		 { "Skirt" },		"SK_SL_06" },
	{ "a01_J_SK_U_01",		 { "Skirt" },		"SK_U_01" },
	{ "a01_J_SK_U_02",		 { "Skirt" },		"SK_U_02" },
	{ "a01_J_SK_U_03",		 { "Skirt" },		"SK_U_03" },
	{ "a01_J_SK_U_04",		 { "Skirt" },		"SK_U_04" },
	{ "a01_J_SK_U_05",		 { "Skirt" },		"SK_U_05" },
	{ "a01_J_SK_U_06",		 { "Skirt" },		"SK_U_06" },
	{ "a01_J_SK_UR_01",		 { "Skirt" },		"SK_UR_01" },
	{ "a01_J_SK_UR_02",		 { "Skirt" },		"SK_UR_02" },
	{ "a01_J_SK_UR_03",		 { "Skirt" },		"SK_UR_03" },
	{ "a01_J_SK_UR_04",		 { "Skirt" },		"SK_UR_04" },
	{ "a01_J_SK_UR_05",		 { "Skirt" },		"SK_UR_05" },
	{ "a01_J_SK_UR_06",		 { "Skirt" },		"SK_UR_06" },
	{ "a01_J_SK_UL_01",		 { "Skirt" },		"SK_UL_01" },
	{ "a01_J_SK_UL_02",		 { "Skirt" },		"SK_UL_02" },
	{ "a01_J_SK_UL_03",		 { "Skirt" },		"SK_UL_03" },
	{ "a01_J_SK_UL_04",		 { "Skirt" },		"SK_UL_04" },
	{ "a01_J_SK_UL_05",		 { "Skirt" },		"SK_UL_05" },
	{ "a01_J_SK_UL_06",		 { "Skirt" },		"SK_UL_06" },
}
