-- Notes:
-- Friendly names must be unique
-- Bones are shown in the poser as ordered here
return {
	{ "a01_N_Zentai_010",	 { "Torso" },		"World" },
	{ "a01_N_Skeleton_010",	 { "Torso" },		"Skeleton" },
	{ "a01_J_Spin_021",		 { "Torso" },		"Neck Base" },
	{ "a01_J_Neck_01",		 { "Torso" },		"Neck 1" },
	{ "a01_J_Neck_02",		 { "Torso" },		"Neck 2" },
	{ "a01_J_Neck_03",		 { "Torso" },		"Head Pivot" },
	{ "a01_J_Hip_010",		 { "Torso" },		"Center" },
	{ "a01_J_Spin_020",		 { "Torso" },		"Chest" },
	{ "a01_J_Spin_010",		 { "Torso" },		"Waist" },
	{ "a01_J_Kosi_010",		 { "Torso" },		"Hip" },
	{ "a01_J_Kosi_020",		 { "Torso" },		"Hip Bottom" },
	{ "a01_J_SiriL_010",		 { "Torso" },		"Ass Cheek Left" },
	{ "a01_J_SiriR_010",		 { "Torso" },		"Ass Cheek Right" },
	{ "a01_J_NikuL_00",		 { "Torso" },		"Left Vagina Lip" },
	{ "a01_J_NikuR_00",		 { "Torso" },		"Right Vagina Lip" },
	{ "a_J_dan00",				 { "Torso" },		"Strapon0" },
	{ "a_J_dan01",				 { "Torso" },		"Strapon1" },
	{ "a_J_dan02",				 { "Torso" },		"Strapon2" },
	{ "a_J_dan03",				 { "Torso" },		"Strapon3" },
	{ "a_J_dan04",				 { "Torso" },		"Strapon4" },
	{ "a_J_dan05",				 { "Torso" },		"Strapon5" },
	{ "a_J_dan06",				 { "Torso" },		"Strapon6" },
	{ "a_J_dan07",				 { "Torso" },		"Strapon7" },
	{ "a_J_dan08",				 { "Torso" },		"Strapon8" },
	{ "a_J_dan09",				 { "Torso" },		"Strapon9" },

	{ "a01_J_ArmL_00",		 { "Left Arm" },		"Left Arm Anchor" },
	{ "a01_J_ArmL_02",		 { "Left Arm" },		"Left Arm Pit" },
	{ "a01_J_ArmL_01",		 { "Left Arm" },		"Left Arm" },
	{ "a01_J_KataL_01",		 { "Left Arm" },		"Left Shoulder 1" },
	{ "a01_J_KataL_02",		 { "Left Arm" },		"Left Shoulder 2" },
	{ "a01_J_UdeL_01",		 { "Left Arm" },		"Left Underarm " },
	{ "a01_J_UdeL_02",		 { "Left Arm" },		"Left Underarm 2" },
	{ "a01_J_HijiL_01",		 { "Left Arm" },		"Left Elbow" },
	{ "a01_J_TekubiL_01",	 { "Left Arm" },		"Left Wrist" },

	{ "a01_J_ArmR_00",		 { "Right Arm" },		"Right Arm Anchor" },
	{ "a01_J_ArmR_02",		 { "Right Arm" },		"Right Arm Pit" },
	{ "a01_J_ArmR_01",		 { "Right Arm" },		"Right Arm" },
	{ "a01_J_KataR_01",		 { "Right Arm" },		"Right Shoulder 1" },
	{ "a01_J_KataR_02",		 { "Right Arm" },		"Right Shoulder 2" },
	{ "a01_J_UdeR_01",		 { "Right Arm" },		"Right Underarm " },
	{ "a01_J_UdeR_02",		 { "Right Arm" },		"Right Underarm 2" },
	{ "a01_J_HijiR_01",		 { "Right Arm" },		"Right Elbow" },
	{ "a01_J_TekubiR_01",	 { "Right Arm" },		"Right Wrist" },
	
	{ "a01_J_HandL_01",		 { "Left Arm", "Left Hand" },		"Left Hand" },
	{ "a01_J_HandL_02",		 { "Left Hand" },		"Left Hand 2" },
	{ "a01_J_HitoL_01",		 { "Left Hand" },		"Left Index Finger 1" },
	{ "a01_J_HitoL_02",		 { "Left Hand" },		"Left Index Finger 2" },
	{ "a01_J_HitoL_03",		 { "Left Hand" },		"Left Index Finger 3" },
	{ "a01_J_NakaL_01",		 { "Left Hand" },		"Left Middle Finger 1" },
	{ "a01_J_NakaL_02",		 { "Left Hand" },		"Left Middle Finger 2" },
	{ "a01_J_NakaL_03",		 { "Left Hand" },		"Left Middle Finger 3" },
	{ "a01_J_KusuriL_01",	 { "Left Hand" },		"Left Ring Finger 1" },
	{ "a01_J_KusuriL_02",	 { "Left Hand" },		"Left Ring Finger 2" },
	{ "a01_J_KusuriL_03",	 { "Left Hand" },		"Left Ring Finger 3" },
	{ "a01_J_KoL_01",			 { "Left Hand" },		"Left Little Finger 1" },
	{ "a01_J_KoL_02",			 { "Left Hand" },		"Left Little Finger 2" },
	{ "a01_J_KoL_03",			 { "Left Hand" },		"Left Little Finger 3" },
	{ "a01_J_OyaL_01",		 { "Left Hand" },		"Left Thumb 1" },
	{ "a01_J_OyaL_02",		 { "Left Hand" },		"Left Thumb 2" },
	{ "a01_J_OyaL_03",		 { "Left Hand" },		"Left Thumb 3" },

	{ "a01_J_HandR_01",		 { "Right Arm", "Right Hand" },		"Right Hand" },
	{ "a01_J_HandR_02",		 { "Right Hand" },		"Right Hand 2" },
	{ "a01_J_HitoR_01",		 { "Right Hand" },		"Right Index Finger 1" },
	{ "a01_J_HitoR_02",		 { "Right Hand" },		"Right Index Finger 2" },
	{ "a01_J_HitoR_03",		 { "Right Hand" },		"Right Index Finger 3" },
	{ "a01_J_NakaR_01",		 { "Right Hand" },		"Right Middle Finger 1" },
	{ "a01_J_NakaR_02",		 { "Right Hand" },		"Right Middle Finger 2" },
	{ "a01_J_NakaR_03",		 { "Right Hand" },		"Right Middle Finger 3" },
	{ "a01_J_KusuriR_01",	 { "Right Hand" },		"Right Ring Finger 1" },
	{ "a01_J_KusuriR_02",	 { "Right Hand" },		"Right Ring Finger 2" },
	{ "a01_J_KusuriR_03",	 { "Right Hand" },		"Right Ring Finger 3" },
	{ "a01_J_KoR_01",			 { "Right Hand" },		"Right Little Finger 1" },
	{ "a01_J_KoR_02",			 { "Right Hand" },		"Right Little Finger 2" },
	{ "a01_J_KoR_03",			 { "Right Hand" },		"Right Little Finger 3" },
	{ "a01_J_OyaR_01",		 { "Right Hand" },		"Right Thumb 1" },
	{ "a01_J_OyaR_02",		 { "Right Hand" },		"Right Thumb 2" },
	{ "a01_J_OyaR_03",		 { "Right Hand" },		"Right Thumb 3" },

	{ "a01_J_UplegL_010",	 { "Left Leg" },		"Left Upper Leg 1" },
	{ "a01_J_UplegL_020",	 { "Left Leg" },		"Left Upper Leg 2" },
	{ "a01_J_LegL_01",		 { "Left Leg" },		"Left Lower Leg" },
	{ "a01_J_HizaL_01",		 { "Left Leg" },		"Left Knee" },
	{ "a01_J_FootL_02",		 { "Left Leg" },		"Left Foot 1" },
	{ "a01_J_FootL_03",		 { "Left Leg" },		"Left Foot 2" },
	{ "a01_J_ToesL_01",		 { "Left Leg" },		"Left Toes" },

	{ "a01_J_UplegR_010",	 { "Right Leg" },		"Right Upper Leg 1" },
	{ "a01_J_UplegR_020",	 { "Right Leg" },		"Right Upper Leg 2" },
	{ "a01_J_LegR_01",		 { "Right Leg" },		"Right Lower Leg" },
	{ "a01_J_HizaR_01",		 { "Right Leg" },		"Right Knee" },
	{ "a01_J_FootR_02",		 { "Right Leg" },		"Right Foot 1" },
	{ "a01_J_FootR_03",		 { "Right Leg" },		"Right Foot 2" },
	{ "a01_J_ToesR_01",		 { "Right Leg" },		"Right Toes" },

	{ "a01_J_MuneR_01",		 { "Breasts" },	"Right Breast 1" },
	{ "a01_J_MuneR_02",		 { "Breasts" },	"Right Breast 2" },
	{ "a01_J_MuneL_01",		 { "Breasts" },	"Left Breast 1" },
	{ "a01_J_MuneL_02",		 { "Breasts" },	"Left Breast 2" },
--	 Leave out until nipples stop glitching
--	{ "a01_J_ChikuR_01",	 { "Breasts" },	"Right Nipple 1" },
--	{ "a01_J_ChikuR_02",	 { "Breasts" },	"Right Nipple 2" },
--	{ "a01_J_ChikuL_01",		 { "Breasts" },	"Left Nipple 1" },
--	{ "a01_J_ChikuL_02",		 { "Breasts" },	"Left Nipple 2" },

	{ "a_J_dan00",				 { "Other" },		"Strapon0" },
	{ "a_J_dan01",				 { "Other" },		"Strapon1" },
	{ "a_J_dan02",				 { "Other" },		"Strapon2" },
	{ "a_J_dan03",				 { "Other" },		"Strapon3" },
	{ "a_J_dan04",				 { "Other" },		"Strapon4" },
	{ "a_J_dan05",				 { "Other" },		"Strapon5" },
	{ "a_J_dan06",				 { "Other" },		"Strapon6" },
	{ "a_J_dan07",				 { "Other" },		"Strapon7" },
	{ "a_J_dan08",				 { "Other" },		"Strapon8" },
	{ "a_J_dan09",				 { "Other" },		"Strapon9" },
	{ "a01_J_NikuL_00",		 { "Other" },		"Left Vagina Lip" },
	{ "a01_J_NikuR_00",		 { "Other" },		"Right Vagina Lip" },
	{ "a01_J_NikuL_01",		 { "Other" },		"Left Ass Meat" },
	{ "a01_J_NikuR_01",		 { "Other" },		"Right Ass Meat" },

	{ "A00_J_meL1",		 { "Face" },		"Left Eye (Face)" },
	{ "A00_J_meR1",		 { "Face" },		"Right Eye (Face)" },
	{ "A00_J_meLTrsX",		 { "Face" },		"Left Eye (Whole)" },
	{ "A00_J_meRTrsX",		 { "Face" },		"Right Eye (Whole)" },
	{ "A00_N_hitomiL",		 { "Face" },		"Left Iris" },
	{ "A00_N_hitomiR",		 { "Face" },		"Right Iris" },
	{ "S00_N_hitomiL",		 { "Face" },		"Left Iris (M)" },
	{ "S00_N_hitomiR",		 { "Face" },		"Right Iris (M)" },
	{ "A00_J_mayuLrot",		 { "Face" },		"Left Eyebrow" },
	{ "A00_J_mayuRrot",		 { "Face" },		"Right Eyebrow" },
	{ "AS00_N_megane",		 { "Face" },		"Glasses" },
	{ "A00_J_kuti",				 { "Face" },		"Mouth" },
	{ "A00_J_sita00",			 { "Face" },		"Tongue 1" },
	{ "A00_J_sita01",			 { "Face" },		"Tongue 2" },
	{ "A00_J_sita02",			 { "Face" },		"Tongue 3" },
	{ "A00_J_sita03",			 { "Face" },		"Tongue 4" },
	{ "A00_J_sita04",			 { "Face" },		"Tongue 5" },
	{ "A00_J_sita05",			 { "Face" },		"Tongue 6" },
	{ "A00_J_sita06",			 { "Face" },		"Tongue 7" },
--	{ "A00_O_namida",		 { "Face" },		"Tears" },
	
	{ "a01_J_SK_F_01",		 { "Skirt" },		"SK_F_01" },
	{ "a01_J_SK_F_02",		 { "Skirt" },		"SK_F_02" },
	{ "a01_J_SK_F_03",		 { "Skirt" },		"SK_F_03" },
	{ "a01_J_SK_F_04",		 { "Skirt" },		"SK_F_04" },
	{ "a01_J_SK_FR_01",		 { "Skirt" },		"SK_FR_01" },
	{ "a01_J_SK_FR_02",		 { "Skirt" },		"SK_FR_02" },
	{ "a01_J_SK_FR_03",		 { "Skirt" },		"SK_FR_03" },
	{ "a01_J_SK_FR_04",		 { "Skirt" },		"SK_FR_04" },
	{ "a01_J_SK_FL_01",		 { "Skirt" },		"SK_FL_01" },
	{ "a01_J_SK_FL_02",		 { "Skirt" },		"SK_FL_02" },
	{ "a01_J_SK_FL_03",		 { "Skirt" },		"SK_FL_03" },
	{ "a01_J_SK_FL_04",		 { "Skirt" },		"SK_FL_04" },
	{ "a01_J_SK_SR_01",		 { "Skirt" },		"SK_SR_01" },
	{ "a01_J_SK_SR_02",		 { "Skirt" },		"SK_SR_02" },
	{ "a01_J_SK_SR_03",		 { "Skirt" },		"SK_SR_03" },
	{ "a01_J_SK_SR_04",		 { "Skirt" },		"SK_SR_04" },
	{ "a01_J_SK_SL_01",		 { "Skirt" },		"SK_SL_01" },
	{ "a01_J_SK_SL_02",		 { "Skirt" },		"SK_SL_02" },
	{ "a01_J_SK_SL_03",		 { "Skirt" },		"SK_SL_03" },
	{ "a01_J_SK_SL_04",		 { "Skirt" },		"SK_SL_04" },
	{ "a01_J_SK_U_01",		 { "Skirt" },		"SK_U_01" },
	{ "a01_J_SK_U_02",		 { "Skirt" },		"SK_U_02" },
	{ "a01_J_SK_U_03",		 { "Skirt" },		"SK_U_03" },
	{ "a01_J_SK_U_04",		 { "Skirt" },		"SK_U_04" },
	{ "a01_J_SK_UR_01",		 { "Skirt" },		"SK_UR_01" },
	{ "a01_J_SK_UR_02",		 { "Skirt" },		"SK_UR_02" },
	{ "a01_J_SK_UR_03",		 { "Skirt" },		"SK_UR_03" },
	{ "a01_J_SK_UR_04",		 { "Skirt" },		"SK_UR_04" },
	{ "a01_J_SK_UL_01",		 { "Skirt" },		"SK_UL_01" },
	{ "a01_J_SK_UL_02",		 { "Skirt" },		"SK_UL_02" },
	{ "a01_J_SK_UL_03",		 { "Skirt" },		"SK_UL_03" },
	{ "a01_J_SK_UL_04",		 { "Skirt" },		"SK_UL_04" },
}
