#include "NamedConstant.h"

namespace Shared {
namespace Triggers {

std::wstring g_NamedConstantCategories[NCONSTCAT_N] {
	TEXT("Relationship"),
	TEXT("Conversation"),
	TEXT("Trait")
};

std::vector<NamedConstant> g_NamedConstants[N_TYPES] = {
	{ //INVALID
		
	},
	{ //INT
		{
			1, NCONSTCAT_RELATIONSHIP, 
			TEXT("Love Points"), TEXT("LOVE"), TEXT("Love points"),
			Value(0)
		},
		{
			2, NCONSTCAT_RELATIONSHIP,
			TEXT("Like Points"), TEXT("LIKE"), TEXT("Like points"),
			Value(1)
		},
		{
			3, NCONSTCAT_RELATIONSHIP,
			TEXT("Dislike Points"), TEXT("DISLIKE"), TEXT("Dislike points"),
			Value(2)
		},
		{
			4, NCONSTCAT_RELATIONSHIP,
			TEXT("Hate Points"), TEXT("HATE"), TEXT("Hate points"),
			Value(3)
		},
		{
			5, NCONSTCAT_CONVERSATIONS,
			TEXT("ENCOURAGE"), TEXT("ENCOURAGE"), TEXT("ENCOURAGE"),
			Value(0)
		},
		{
			6, NCONSTCAT_CONVERSATIONS,
				TEXT("CALM"), TEXT("CALM"), TEXT("CALM"),
				Value(1)
		},
		{
			7, NCONSTCAT_CONVERSATIONS,
				TEXT("PRAISE"), TEXT("PRAISE"), TEXT("PRAISE"),
				Value(2)
		},
		{
			8, NCONSTCAT_CONVERSATIONS,
				TEXT("GRUMBLE"), TEXT("GRUMBLE"), TEXT("GRUMBLE"),
				Value(3)
		},
		{
			9, NCONSTCAT_CONVERSATIONS,
				TEXT("APOLOGIZE"), TEXT("APOLOGIZE"), TEXT("APOLOGIZE"),
				Value(4)
		},
		{
			10, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_STUDY"), TEXT("MAKE_STUDY"), TEXT("MAKE_STUDY"),
				Value(5)
		},
		{
			11, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_EXERCISE"), TEXT("MAKE_EXERCISE"), TEXT("MAKE_EXERCISE"),
				Value(6)
		},
		{
			12, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_CLUB"), TEXT("MAKE_CLUB"), TEXT("MAKE_CLUB"),
				Value(7)
		},
		{
			13, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_GET_ALONG"), TEXT("MAKE_GET_ALONG"), TEXT("MAKE_GET_ALONG"),
				Value(8)
		},
		{
			14, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_NO_PUBLIC_LEWD"), TEXT("MAKE_NO_PUBLIC_LEWD"), TEXT("MAKE_NO_PUBLIC_LEWD"),
				Value(9)
		},
		{
			15, NCONSTCAT_CONVERSATIONS,
				TEXT("GOOD_RUMOR"), TEXT("GOOD_RUMOR"), TEXT("GOOD_RUMOR"),
				Value(10)
		},
		{
			16, NCONSTCAT_CONVERSATIONS,
				TEXT("GET_ALONG_WITH"), TEXT("GET_ALONG_WITH"), TEXT("GET_ALONG_WITH"),
				Value(11)
		},
		{
			17, NCONSTCAT_CONVERSATIONS,
				TEXT("I_WANNA_GET_ALONG_WITH"), TEXT("I_WANNA_GET_ALONG_WITH"), TEXT("I_WANNA_GET_ALONG_WITH"),
				Value(12)
		},
		{
			18, NCONSTCAT_CONVERSATIONS,
				TEXT("BAD_RUMOR"), TEXT("BAD_RUMOR"), TEXT("BAD_RUMOR"),
				Value(13)
		},
		{
			19, NCONSTCAT_CONVERSATIONS,
				TEXT("DO_YOU_LIKE"), TEXT("DO_YOU_LIKE"), TEXT("DO_YOU_LIKE"),
				Value(14)
		},
		{
			20, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LIFE"), TEXT("TALK_LIFE"), TEXT("TALK_LIFE"),
				Value(15)
		},
		{
			21, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_HOBBIES"), TEXT("TALK_HOBBIES"), TEXT("TALK_HOBBIES"),
				Value(16)
		},
		{
			22, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_FOOD"), TEXT("TALK_FOOD"), TEXT("TALK_FOOD"),
				Value(17)
		},
		{
			23, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LOVE"), TEXT("TALK_LOVE"), TEXT("TALK_LOVE"),
				Value(18)
		},
		{
			24, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LEWD"), TEXT("TALK_LEWD"), TEXT("TALK_LEWD"),
				Value(19)
		},
		{
			25, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_TOGETHER"), TEXT("STUDY_TOGETHER"), TEXT("STUDY_TOGETHER"),
				Value(20)
		},
		{
			26, NCONSTCAT_CONVERSATIONS,
				TEXT("EXERCISE_TOGETHER"), TEXT("EXERCISE_TOGETHER"), TEXT("EXERCISE_TOGETHER"),
				Value(21)
		},
		{
			27, NCONSTCAT_CONVERSATIONS,
				TEXT("CLUB_TOGETHER"), TEXT("CLUB_TOGETHER"), TEXT("CLUB_TOGETHER"),
				Value(22)
		},
		{
			28, NCONSTCAT_CONVERSATIONS,
				TEXT("MASSAGE"), TEXT("MASSAGE"), TEXT("MASSAGE"),
				Value(23)
		},
		{
			29, NCONSTCAT_CONVERSATIONS,
				TEXT("GOTO_CLASS"), TEXT("GOTO_CLASS"), TEXT("GOTO_CLASS"),
				Value(24)
		},
		{
			30, NCONSTCAT_CONVERSATIONS,
				TEXT("LUNCH_TOGETHER"), TEXT("LUNCH_TOGETHER"), TEXT("LUNCH_TOGETHER"),
				Value(25)
		},
		{
			31, NCONSTCAT_CONVERSATIONS,
				TEXT("TEA_TOGETHER"), TEXT("TEA_TOGETHER"), TEXT("TEA_TOGETHER"),
				Value(26)
		},
		{
			32, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_HOME_TOGETHER"), TEXT("GO_HOME_TOGETHER"), TEXT("GO_HOME_TOGETHER"),
				Value(27)
		},
		{
			33, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_PLAY_TOGETHER"), TEXT("GO_PLAY_TOGETHER"), TEXT("GO_PLAY_TOGETHER"),
				Value(28)
		},
		{
			34, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_EAT_TOGETHER"), TEXT("GO_EAT_TOGETHER"), TEXT("GO_EAT_TOGETHER"),
				Value(29)
		},
		{
			35, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_KARAOKE_TOGETHER"), TEXT("GO_KARAOKE_TOGETHER"), TEXT("GO_KARAOKE_TOGETHER"),
				Value(30)
		},
		{
			36, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_HOME"), TEXT("STUDY_HOME"), TEXT("STUDY_HOME"),
				Value(31)
		},
		{
			37, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_HOME_H"), TEXT("STUDY_HOME_H"), TEXT("STUDY_HOME_H"),
				Value(32)
		},
		{
			38, NCONSTCAT_CONVERSATIONS,
				TEXT("INSULT"), TEXT("INSULT"), TEXT("INSULT"),
				Value(33)
		},
		{
			39, NCONSTCAT_CONVERSATIONS,
				TEXT("FIGHT"), TEXT("FIGHT"), TEXT("FIGHT"),
				Value(34)
		},
		{
			40, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_IGNORE"), TEXT("MAKE_IGNORE"), TEXT("MAKE_IGNORE"),
				Value(35)
		},
		{
			41, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_SHOW_THAT"), TEXT("FORCE_SHOW_THAT"), TEXT("FORCE_SHOW_THAT"),
				Value(36)
		},
		{
			42, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_PUT_THIS_ON"), TEXT("FORCE_PUT_THIS_ON"), TEXT("FORCE_PUT_THIS_ON"),
				Value(37)
		},
		{
			43, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_H"), TEXT("FORCE_H"), TEXT("FORCE_H"),
				Value(38)
		},
		{
			44, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_JOIN_CLUB"), TEXT("MAKE_JOIN_CLUB"), TEXT("MAKE_JOIN_CLUB"),
				Value(39)
		},
		{
			45, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_DATE"), TEXT("ASK_DATE"), TEXT("ASK_DATE"),
				Value(40)
		},
		{
			46, NCONSTCAT_CONVERSATIONS,
				TEXT("CONFESS"), TEXT("CONFESS"), TEXT("CONFESS"),
				Value(41)
		},
		{
			47, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_COUPLE"), TEXT("ASK_COUPLE"), TEXT("ASK_COUPLE"),
				Value(42)
		},
		{
			48, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_BREAKUP"), TEXT("ASK_BREAKUP"), TEXT("ASK_BREAKUP"),
				Value(43)
		},
		{
			49, NCONSTCAT_CONVERSATIONS,
				TEXT("HEADPAT"), TEXT("HEADPAT"), TEXT("HEADPAT"),
				Value(44)
		},
		{
			50, NCONSTCAT_CONVERSATIONS,
				TEXT("HUG"), TEXT("HUG"), TEXT("HUG"),
				Value(45)
		},
		{
			51, NCONSTCAT_CONVERSATIONS,
				TEXT("KISS"), TEXT("KISS"), TEXT("KISS"),
				Value(46)
		},
		{
			52, NCONSTCAT_CONVERSATIONS,
				TEXT("TOUCH"), TEXT("TOUCH"), TEXT("TOUCH"),
				Value(47)
		},
		{
			53, NCONSTCAT_CONVERSATIONS,
				TEXT("NORMAL_H"), TEXT("NORMAL_H"), TEXT("NORMAL_H"),
				Value(48)
		},
		{
			54, NCONSTCAT_CONVERSATIONS,
				TEXT("FOLLOW_ME"), TEXT("FOLLOW_ME"), TEXT("FOLLOW_ME"),
				Value(49)
		},
		{
			55, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_AWAY"), TEXT("GO_AWAY"), TEXT("GO_AWAY"),
				Value(50)
		},
		{
			56, NCONSTCAT_CONVERSATIONS,
				TEXT("COME_TO"), TEXT("COME_TO"), TEXT("COME_TO"),
				Value(51)
		},
		{
			57, NCONSTCAT_CONVERSATIONS,
				TEXT("COMPETE"), TEXT("COMPETE"), TEXT("COMPETE"),
				Value(63)
		},
		{
			58, NCONSTCAT_CONVERSATIONS,
				TEXT("REQUEST_MASSAGE"), TEXT("REQUEST_MASSAGE"), TEXT("REQUEST_MASSAGE"),
				Value(69)
		},
		{
			59, NCONSTCAT_CONVERSATIONS,
				TEXT("REQEUST_KISS"), TEXT("REQEUST_KISS"), TEXT("REQEUST_KISS"),
				Value(70)
		},
		{
			60, NCONSTCAT_CONVERSATIONS,
				TEXT("REQUEST_HUG"), TEXT("REQUEST_HUG"), TEXT("REQUEST_HUG"),
				Value(71)
		},
		{
			61, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS"), TEXT("SKIP_CLASS"), TEXT("SKIP_CLASS"),
				Value(72)
		},
		{
			62, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS_H"), TEXT("SKIP_CLASS_H"), TEXT("SKIP_CLASS_H"),
				Value(73)
		},
		{
			63, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS_SURPRISE_H"), TEXT("SKIP_CLASS_SURPRISE_H"), TEXT("SKIP_CLASS_SURPRISE_H"),
				Value(74)
		},
		{
			64, NCONSTCAT_CONVERSATIONS,
				TEXT("DID_YOU_HAVE_H"), TEXT("DID_YOU_HAVE_H"), TEXT("DID_YOU_HAVE_H"),
				Value(75)
		},
		{
			65, NCONSTCAT_CONVERSATIONS,
				TEXT("SHOW_UNDERWEAR"), TEXT("SHOW_UNDERWEAR"), TEXT("SHOW_UNDERWEAR"),
				Value(76)
		},
		{
			66, NCONSTCAT_CONVERSATIONS,
				TEXT("HAVE_YOU_HAD_H"), TEXT("HAVE_YOU_HAD_H"), TEXT("HAVE_YOU_HAD_H"),
				Value(77)
		},
		{
			67, NCONSTCAT_CONVERSATIONS,
				TEXT("EXCHANGE_ITEMS"), TEXT("EXCHANGE_ITEMS"), TEXT("EXCHANGE_ITEMS"),
				Value(78)
		},
		{
			68, NCONSTCAT_CONVERSATIONS,
				TEXT("LEWD_PROMISE"), TEXT("LEWD_PROMISE"), TEXT("LEWD_PROMISE"),
				Value(79)
		},
		{
			69, NCONSTCAT_CONVERSATIONS,
				TEXT("AWARD_LEWD_PROMISE"), TEXT("AWARD_LEWD_PROMISE"), TEXT("AWARD_LEWD_PROMISE"),
				Value(80)
		},
		{
			70, NCONSTCAT_CONVERSATIONS,
				TEXT("EXPLOITABLE_LINE"), TEXT("EXPLOITABLE_LINE"), TEXT("EXPLOITABLE_LINE"),
				Value(90)
		},
		{
			71, NCONSTCAT_CONVERSATIONS,
				TEXT("NO_PROMPT_H"), TEXT("NO_PROMPT_H"), TEXT("NO_PROMPT_H"),
				Value(99)
		},
		{
			72, NCONSTCAT_CONVERSATIONS,
				TEXT("AFTER_H"), TEXT("AFTER_H"), TEXT("AFTER_H"),
				Value(101)
		},
		{
			73, NCONSTCAT_TRAIT,
			TEXT("EASYGOING"), TEXT("EASYGOING"), TEXT("EASYGOING"),
			Value(0)
		},
		{
			74, NCONSTCAT_TRAIT,
			TEXT("AFFABLE"), TEXT("AFFABLE"), TEXT("AFFABLE"),
			Value(1)
		},
		{
			75, NCONSTCAT_TRAIT,
			TEXT("BAD_WITH_GUYS"), TEXT("BAD_WITH_GUYS"), TEXT("BAD_WITH_GUYS"),
			Value(2)
		},
		{
			76, NCONSTCAT_TRAIT,
			TEXT("BAD_WITH_GIRLS"), TEXT("BAD_WITH_GIRLS"), TEXT("BAD_WITH_GIRLS"),
			Value(3)
		},
		{
			77, NCONSTCAT_TRAIT,
			TEXT("CHARMING"), TEXT("CHARMING"), TEXT("CHARMING"),
			Value(4)
		},
		{
			78, NCONSTCAT_TRAIT,
			TEXT("TSUNDERE"), TEXT("TSUNDERE"), TEXT("TSUNDERE"),
			Value(5)
		},
		{
			79, NCONSTCAT_TRAIT,
			TEXT("CHIVALROUS"), TEXT("CHIVALROUS"), TEXT("CHIVALROUS"),
			Value(6)
		},
		{
			80, NCONSTCAT_TRAIT,
			TEXT("TRENDY"), TEXT("TRENDY"), TEXT("TRENDY"),
			Value(7)
		},
		{
			81, NCONSTCAT_TRAIT,
			TEXT("OBEDIENT"), TEXT("OBEDIENT"), TEXT("OBEDIENT"),
			Value(8)
		},
		{
			82, NCONSTCAT_TRAIT,
			TEXT("POSITIVE"), TEXT("POSITIVE"), TEXT("POSITIVE"),
			Value(9)
		},
		{
			83, NCONSTCAT_TRAIT,
			TEXT("SHY"), TEXT("SHY"), TEXT("SHY"),
			Value(10)
		},
		{
			84, NCONSTCAT_TRAIT,
			TEXT("JEALOUS"), TEXT("JEALOUS"), TEXT("JEALOUS"),
			Value(11)
		},
		{
			85, NCONSTCAT_TRAIT,
			TEXT("MELANCHOLY"), TEXT("MELANCHOLY"), TEXT("MELANCHOLY"),
			Value(12)
		},
		{
			86, NCONSTCAT_TRAIT,
			TEXT("PERVERTED"), TEXT("PERVERTED"), TEXT("PERVERTED"),
			Value(13)
		},
		{
			87, NCONSTCAT_TRAIT,
			TEXT("SERIOUS"), TEXT("SERIOUS"), TEXT("SERIOUS"),
			Value(14)
		},
		{
			88, NCONSTCAT_TRAIT,
			TEXT("CALM"), TEXT("CALM"), TEXT("CALM"),
			Value(15)
		},
		{
			89, NCONSTCAT_TRAIT,
			TEXT("IMPULSIVE"), TEXT("IMPULSIVE"), TEXT("IMPULSIVE"),
			Value(16)
		},
		{
			90, NCONSTCAT_TRAIT,
			TEXT("ABSENTMINDED"), TEXT("ABSENTMINDED"), TEXT("ABSENTMINDED"),
			Value(17)
		},
		{
			91, NCONSTCAT_TRAIT,
			TEXT("VIOLENT"), TEXT("VIOLENT"), TEXT("VIOLENT"),
			Value(18)
		},
		{
			92, NCONSTCAT_TRAIT,
			TEXT("PASSIVE"), TEXT("PASSIVE"), TEXT("PASSIVE"),
			Value(19)
		},
		{
			93, NCONSTCAT_TRAIT,
			TEXT("MEDDLESOME"), TEXT("MEDDLESOME"), TEXT("MEDDLESOME"),
			Value(20)
		},
		{
			94, NCONSTCAT_TRAIT,
			TEXT("CLASS_PREZ"), TEXT("CLASS_PREZ"), TEXT("CLASS_PREZ"),
			Value(21)
		},
		{
			95, NCONSTCAT_TRAIT,
			TEXT("CHATTY"), TEXT("CHATTY"), TEXT("CHATTY"),
			Value(22)
		},
		{
			96, NCONSTCAT_TRAIT,
			TEXT("ALWAYS_HUNGRY"), TEXT("ALWAYS_HUNGRY"), TEXT("ALWAYS_HUNGRY"),
			Value(23)
		},
		{
			97, NCONSTCAT_TRAIT,
			TEXT("ROMANTIC"), TEXT("ROMANTIC"), TEXT("ROMANTIC"),
			Value(24)
		},
		{
			98, NCONSTCAT_TRAIT,
			TEXT("SINGLEMINDED"), TEXT("SINGLEMINDED"), TEXT("SINGLEMINDED"),
			Value(25)
		},
		{
			99, NCONSTCAT_TRAIT,
			TEXT("INDECISIVE"), TEXT("INDECISIVE"), TEXT("INDECISIVE"),
			Value(26)
		},
		{
			100, NCONSTCAT_TRAIT,
			TEXT("COMPETITIVE"), TEXT("COMPETITIVE"), TEXT("COMPETITIVE"),
			Value(27)
		},
		{
			101, NCONSTCAT_TRAIT,
			TEXT("SCHEMING"), TEXT("SCHEMING"), TEXT("SCHEMING"),
			Value(28)
		},
		{
			102, NCONSTCAT_TRAIT,
			TEXT("DILIGENT"), TEXT("DILIGENT"), TEXT("DILIGENT"),
			Value(29)
		},
		{
			103, NCONSTCAT_TRAIT,
			TEXT("WILD"), TEXT("WILD"), TEXT("WILD"),
			Value(30)
		},
		{
			104, NCONSTCAT_TRAIT,
			TEXT("MASOCHIST"), TEXT("MASOCHIST"), TEXT("MASOCHIST"),
			Value(31)
		},
		{
			105, NCONSTCAT_TRAIT,
			TEXT("SWEATY"), TEXT("SWEATY"), TEXT("SWEATY"),
			Value(32)
		},
		{
			106, NCONSTCAT_TRAIT,
			TEXT("EVIL"), TEXT("EVIL"), TEXT("EVIL"),
			Value(33)
		},
		{
			107, NCONSTCAT_TRAIT,
			TEXT("DEAF"), TEXT("DEAF"), TEXT("DEAF"),
			Value(34)
		},
		{
			108, NCONSTCAT_TRAIT,
			TEXT("EXPLOITABLE"), TEXT("EXPLOITABLE"), TEXT("EXPLOITABLE"),
			Value(35)
		},
		{
			109, NCONSTCAT_TRAIT,
			TEXT("ASEXUAL"), TEXT("ASEXUAL"), TEXT("ASEXUAL"),
			Value(36)
		},
		{
			110, NCONSTCAT_TRAIT,
			TEXT("LUCKY"), TEXT("LUCKY"), TEXT("LUCKY"),
			Value(37)
		},
		{
			111, NCONSTCAT_TRAIT,
			TEXT("RAINBOW"), TEXT("RAINBOW"), TEXT("RAINBOW"),
			Value(38)
		},
	},
	{ //BOOL
		
	},
	{ //FLOAT
		
	},
	{ //STRING
		
	}

};






}
}