#include "NamedConstant.h"
#include "External\ExternalClasses\ConversationStruct.h"



namespace Shared {
namespace Triggers {

std::wstring g_NamedConstantCategories[NCONSTCAT_N] {
	TEXT("Relationship"),
	TEXT("Conversation"),
	TEXT("Trait")
};

std::vector<NamedConstant> g_NamedConstants[N_TYPES] = {
	{ //INVALID
		
	},
	{ //INT
		//Relationship
		{
			1, NCONSTCAT_RELATIONSHIP, 
			TEXT("Love Points"), TEXT("LOVE"), TEXT("Love points"),
			Value(0)
		},
		{
			2, NCONSTCAT_RELATIONSHIP,
			TEXT("Like Points"), TEXT("LIKE"), TEXT("Like points"),
			Value(1)
		},
		{
			3, NCONSTCAT_RELATIONSHIP,
			TEXT("Dislike Points"), TEXT("DISLIKE"), TEXT("Dislike points"),
			Value(2)
		},
		{
			4, NCONSTCAT_RELATIONSHIP,
			TEXT("Hate Points"), TEXT("HATE"), TEXT("Hate points"),
			Value(3)
		},
		//Conversation
		{
			5, NCONSTCAT_CONVERSATIONS,
			TEXT("ENCOURAGE"), TEXT("ENCOURAGE"), TEXT("ENCOURAGE"),
			Value(0)
		},
		{
			6, NCONSTCAT_CONVERSATIONS,
				TEXT("CALM"), TEXT("CALM"), TEXT("CALM"),
				Value(1)
		},
		{
			7, NCONSTCAT_CONVERSATIONS,
				TEXT("PRAISE"), TEXT("PRAISE"), TEXT("PRAISE"),
				Value(2)
		},
		{
			8, NCONSTCAT_CONVERSATIONS,
				TEXT("GRUMBLE"), TEXT("GRUMBLE"), TEXT("GRUMBLE"),
				Value(3)
		},
		{
			9, NCONSTCAT_CONVERSATIONS,
				TEXT("APOLOGIZE"), TEXT("APOLOGIZE"), TEXT("APOLOGIZE"),
				Value(4)
		},
		{
			10, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_STUDY"), TEXT("MAKE_STUDY"), TEXT("MAKE_STUDY"),
				Value(5)
		},
		{
			11, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_EXERCISE"), TEXT("MAKE_EXERCISE"), TEXT("MAKE_EXERCISE"),
				Value(6)
		},
		{
			12, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_CLUB"), TEXT("MAKE_CLUB"), TEXT("MAKE_CLUB"),
				Value(7)
		},
		{
			13, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_GET_ALONG"), TEXT("MAKE_GET_ALONG"), TEXT("MAKE_GET_ALONG"),
				Value(8)
		},
		{
			14, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_NO_PUBLIC_LEWD"), TEXT("MAKE_NO_PUBLIC_LEWD"), TEXT("MAKE_NO_PUBLIC_LEWD"),
				Value(9)
		},
		{
			15, NCONSTCAT_CONVERSATIONS,
				TEXT("GOOD_RUMOR"), TEXT("GOOD_RUMOR"), TEXT("GOOD_RUMOR"),
				Value(10)
		},
		{
			16, NCONSTCAT_CONVERSATIONS,
				TEXT("GET_ALONG_WITH"), TEXT("GET_ALONG_WITH"), TEXT("GET_ALONG_WITH"),
				Value(11)
		},
		{
			17, NCONSTCAT_CONVERSATIONS,
				TEXT("I_WANNA_GET_ALONG_WITH"), TEXT("I_WANNA_GET_ALONG_WITH"), TEXT("I_WANNA_GET_ALONG_WITH"),
				Value(12)
		},
		{
			18, NCONSTCAT_CONVERSATIONS,
				TEXT("BAD_RUMOR"), TEXT("BAD_RUMOR"), TEXT("BAD_RUMOR"),
				Value(13)
		},
		{
			19, NCONSTCAT_CONVERSATIONS,
				TEXT("DO_YOU_LIKE"), TEXT("DO_YOU_LIKE"), TEXT("DO_YOU_LIKE"),
				Value(14)
		},
		{
			20, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LIFE"), TEXT("TALK_LIFE"), TEXT("TALK_LIFE"),
				Value(15)
		},
		{
			21, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_HOBBIES"), TEXT("TALK_HOBBIES"), TEXT("TALK_HOBBIES"),
				Value(16)
		},
		{
			22, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_FOOD"), TEXT("TALK_FOOD"), TEXT("TALK_FOOD"),
				Value(17)
		},
		{
			23, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LOVE"), TEXT("TALK_LOVE"), TEXT("TALK_LOVE"),
				Value(18)
		},
		{
			24, NCONSTCAT_CONVERSATIONS,
				TEXT("TALK_LEWD"), TEXT("TALK_LEWD"), TEXT("TALK_LEWD"),
				Value(19)
		},
		{
			25, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_TOGETHER"), TEXT("STUDY_TOGETHER"), TEXT("STUDY_TOGETHER"),
				Value(20)
		},
		{
			26, NCONSTCAT_CONVERSATIONS,
				TEXT("EXERCISE_TOGETHER"), TEXT("EXERCISE_TOGETHER"), TEXT("EXERCISE_TOGETHER"),
				Value(21)
		},
		{
			27, NCONSTCAT_CONVERSATIONS,
				TEXT("CLUB_TOGETHER"), TEXT("CLUB_TOGETHER"), TEXT("CLUB_TOGETHER"),
				Value(22)
		},
		{
			28, NCONSTCAT_CONVERSATIONS,
				TEXT("MASSAGE"), TEXT("MASSAGE"), TEXT("MASSAGE"),
				Value(23)
		},
		{
			29, NCONSTCAT_CONVERSATIONS,
				TEXT("GOTO_CLASS"), TEXT("GOTO_CLASS"), TEXT("GOTO_CLASS"),
				Value(24)
		},
		{
			30, NCONSTCAT_CONVERSATIONS,
				TEXT("LUNCH_TOGETHER"), TEXT("LUNCH_TOGETHER"), TEXT("LUNCH_TOGETHER"),
				Value(25)
		},
		{
			31, NCONSTCAT_CONVERSATIONS,
				TEXT("TEA_TOGETHER"), TEXT("TEA_TOGETHER"), TEXT("TEA_TOGETHER"),
				Value(26)
		},
		{
			32, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_HOME_TOGETHER"), TEXT("GO_HOME_TOGETHER"), TEXT("GO_HOME_TOGETHER"),
				Value(27)
		},
		{
			33, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_PLAY_TOGETHER"), TEXT("GO_PLAY_TOGETHER"), TEXT("GO_PLAY_TOGETHER"),
				Value(28)
		},
		{
			34, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_EAT_TOGETHER"), TEXT("GO_EAT_TOGETHER"), TEXT("GO_EAT_TOGETHER"),
				Value(29)
		},
		{
			35, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_KARAOKE_TOGETHER"), TEXT("GO_KARAOKE_TOGETHER"), TEXT("GO_KARAOKE_TOGETHER"),
				Value(30)
		},
		{
			36, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_HOME"), TEXT("STUDY_HOME"), TEXT("STUDY_HOME"),
				Value(31)
		},
		{
			37, NCONSTCAT_CONVERSATIONS,
				TEXT("STUDY_HOME_H"), TEXT("STUDY_HOME_H"), TEXT("STUDY_HOME_H"),
				Value(32)
		},
		{
			38, NCONSTCAT_CONVERSATIONS,
				TEXT("INSULT"), TEXT("INSULT"), TEXT("INSULT"),
				Value(33)
		},
		{
			39, NCONSTCAT_CONVERSATIONS,
				TEXT("FIGHT"), TEXT("FIGHT"), TEXT("FIGHT"),
				Value(34)
		},
		{
			40, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_IGNORE"), TEXT("MAKE_IGNORE"), TEXT("MAKE_IGNORE"),
				Value(35)
		},
		{
			41, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_SHOW_THAT"), TEXT("FORCE_SHOW_THAT"), TEXT("FORCE_SHOW_THAT"),
				Value(36)
		},
		{
			42, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_PUT_THIS_ON"), TEXT("FORCE_PUT_THIS_ON"), TEXT("FORCE_PUT_THIS_ON"),
				Value(37)
		},
		{
			43, NCONSTCAT_CONVERSATIONS,
				TEXT("FORCE_H"), TEXT("FORCE_H"), TEXT("FORCE_H"),
				Value(38)
		},
		{
			44, NCONSTCAT_CONVERSATIONS,
				TEXT("MAKE_JOIN_CLUB"), TEXT("MAKE_JOIN_CLUB"), TEXT("MAKE_JOIN_CLUB"),
				Value(39)
		},
		{
			45, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_DATE"), TEXT("ASK_DATE"), TEXT("ASK_DATE"),
				Value(40)
		},
		{
			46, NCONSTCAT_CONVERSATIONS,
				TEXT("CONFESS"), TEXT("CONFESS"), TEXT("CONFESS"),
				Value(41)
		},
		{
			47, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_COUPLE"), TEXT("ASK_COUPLE"), TEXT("ASK_COUPLE"),
				Value(42)
		},
		{
			48, NCONSTCAT_CONVERSATIONS,
				TEXT("ASK_BREAKUP"), TEXT("ASK_BREAKUP"), TEXT("ASK_BREAKUP"),
				Value(43)
		},
		{
			49, NCONSTCAT_CONVERSATIONS,
				TEXT("HEADPAT"), TEXT("HEADPAT"), TEXT("HEADPAT"),
				Value(44)
		},
		{
			50, NCONSTCAT_CONVERSATIONS,
				TEXT("HUG"), TEXT("HUG"), TEXT("HUG"),
				Value(45)
		},
		{
			51, NCONSTCAT_CONVERSATIONS,
				TEXT("KISS"), TEXT("KISS"), TEXT("KISS"),
				Value(46)
		},
		{
			52, NCONSTCAT_CONVERSATIONS,
				TEXT("TOUCH"), TEXT("TOUCH"), TEXT("TOUCH"),
				Value(47)
		},
		{
			53, NCONSTCAT_CONVERSATIONS,
				TEXT("NORMAL_H"), TEXT("NORMAL_H"), TEXT("NORMAL_H"),
				Value(48)
		},
		{
			54, NCONSTCAT_CONVERSATIONS,
				TEXT("FOLLOW_ME"), TEXT("FOLLOW_ME"), TEXT("FOLLOW_ME"),
				Value(49)
		},
		{
			55, NCONSTCAT_CONVERSATIONS,
				TEXT("GO_AWAY"), TEXT("GO_AWAY"), TEXT("GO_AWAY"),
				Value(50)
		},
		{
			56, NCONSTCAT_CONVERSATIONS,
				TEXT("COME_TO"), TEXT("COME_TO"), TEXT("COME_TO"),
				Value(51)
		},
		{
			57, NCONSTCAT_CONVERSATIONS,
			TEXT("NEVERMIND"), TEXT("NEVERMIND"), TEXT("NEVERMIND"),
			Value(ExtClass::ConversationId::NEVERMIND)
		},
		{
			58, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_STUDY"), TEXT("MINNA_STUDY"), TEXT("MINNA_STUDY"),
			Value(ExtClass::ConversationId::MINNA_STUDY)
		},
		{
			59, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_SPORTS"), TEXT("MINNA_SPORTS"), TEXT("MINNA_SPORTS"),
			Value(ExtClass::ConversationId::MINNA_SPORTS)
		},
		{
			60, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_CLUB"), TEXT("MINNA_CLUB"), TEXT("MINNA_CLUB"),
			Value(ExtClass::ConversationId::MINNA_CLUB)
		},
		{
			61, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_REST"), TEXT("MINNA_REST"), TEXT("MINNA_REST"),
			Value(ExtClass::ConversationId::MINNA_REST)
		},
		{
			62, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_EAT"), TEXT("MINNA_EAT"), TEXT("MINNA_EAT"),
			Value(ExtClass::ConversationId::MINNA_EAT)
		},
		{
			63, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_KARAOKE"), TEXT("MINNA_KARAOKE"), TEXT("MINNA_KARAOKE"),
			Value(ExtClass::ConversationId::MINNA_KARAOKE)
		},
		{
			64, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_BE_FRIENDLY"), TEXT("MINNA_BE_FRIENDLY"), TEXT("MINNA_BE_FRIENDLY"),
			Value(ExtClass::ConversationId::MINNA_BE_FRIENDLY)
		},
		{
			65, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_COME"), TEXT("MINNA_COME"), TEXT("MINNA_COME"),
			Value(ExtClass::ConversationId::MINNA_COME)
		},
		{
			66, NCONSTCAT_CONVERSATIONS,
				TEXT("COMPETE"), TEXT("COMPETE"), TEXT("COMPETE"),
				Value(63)
		},
		{
			67, NCONSTCAT_CONVERSATIONS,
			TEXT("TRY_3P"), TEXT("TRY_3P"), TEXT("TRY_3P"),
			Value(ExtClass::ConversationId::TRY_3P)
		},
		{
			68, NCONSTCAT_CONVERSATIONS,
				TEXT("REQUEST_MASSAGE"), TEXT("REQUEST_MASSAGE"), TEXT("REQUEST_MASSAGE"),
				Value(69)
		},
		{
			69, NCONSTCAT_CONVERSATIONS,
				TEXT("REQUEST_KISS"), TEXT("REQUEST_KISS"), TEXT("REQUEST_KISS"),
				Value(70)
		},
		{
			70, NCONSTCAT_CONVERSATIONS,
				TEXT("REQUEST_HUG"), TEXT("REQUEST_HUG"), TEXT("REQUEST_HUG"),
				Value(71)
		},
		{
			71, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS"), TEXT("SKIP_CLASS"), TEXT("SKIP_CLASS"),
				Value(72)
		},
		{
			72, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS_H"), TEXT("SKIP_CLASS_H"), TEXT("SKIP_CLASS_H"),
				Value(73)
		},
		{
			73, NCONSTCAT_CONVERSATIONS,
				TEXT("SKIP_CLASS_SURPRISE_H"), TEXT("SKIP_CLASS_SURPRISE_H"), TEXT("SKIP_CLASS_SURPRISE_H"),
				Value(74)
		},
		{
			74, NCONSTCAT_CONVERSATIONS,
				TEXT("DID_YOU_HAVE_H"), TEXT("DID_YOU_HAVE_H"), TEXT("DID_YOU_HAVE_H"),
				Value(75)
		},
		{
			75, NCONSTCAT_CONVERSATIONS,
				TEXT("SHOW_UNDERWEAR"), TEXT("SHOW_UNDERWEAR"), TEXT("SHOW_UNDERWEAR"),
				Value(76)
		},
		{
			76, NCONSTCAT_CONVERSATIONS,
				TEXT("DID_YOU_HAVE_H_WITH"), TEXT("DID_YOU_HAVE_H_WITH"), TEXT("DID_YOU_HAVE_H_WITH"),
				Value(ExtClass::ConversationId::DID_YOU_HAVE_H_WITH)
		},
		{
			77, NCONSTCAT_CONVERSATIONS,
				TEXT("EXCHANGE_ITEMS"), TEXT("EXCHANGE_ITEMS"), TEXT("EXCHANGE_ITEMS"),
				Value(78)
		},
		{
			78, NCONSTCAT_CONVERSATIONS,
				TEXT("LEWD_PROMISE"), TEXT("LEWD_PROMISE"), TEXT("LEWD_PROMISE"),
				Value(79)
		},
		{
			79, NCONSTCAT_CONVERSATIONS,
				TEXT("AWARD_LEWD_PROMISE"), TEXT("AWARD_LEWD_PROMISE"), TEXT("AWARD_LEWD_PROMISE"),
				Value(80)
		},
		{
			80, NCONSTCAT_CONVERSATIONS,
			TEXT("TOGETHER_FOREVER"), TEXT("TOGETHER_FOREVER"), TEXT("TOGETHER_FOREVER"),
			Value(ExtClass::ConversationId::TOGETHER_FOREVER)
		},
		{
			81, NCONSTCAT_CONVERSATIONS,
			TEXT("MURDER"), TEXT("MURDER"), TEXT("MURDER"),
			Value(ExtClass::ConversationId::MURDER)
		},
		{
			82, NCONSTCAT_CONVERSATIONS,
			TEXT("SLAP"), TEXT("SLAP"), TEXT("SLAP"),
			Value(ExtClass::ConversationId::SLAP)
		},
		{
			83, NCONSTCAT_CONVERSATIONS,
			TEXT("GOOD_MORNING_KISS"), TEXT("GOOD_MORNING_KISS"), TEXT("GOOD_MORNING_KISS"),
			Value(ExtClass::ConversationId::GOOD_MORNING_KISS)
		},
		{
			84, NCONSTCAT_CONVERSATIONS,
			TEXT("GOOD_BYE_KISS"), TEXT("GOOD_BYE_KISS"), TEXT("GOOD_BYE_KISS"),
			Value(ExtClass::ConversationId::GOOD_BYE_KISS)
		},
		{
			85, NCONSTCAT_CONVERSATIONS,
			TEXT("NO_PROMPT_KISS"), TEXT("NO_PROMPT_KISS"), TEXT("NO_PROMPT_KISS"),
			Value(ExtClass::ConversationId::NO_PROMPT_KISS)
		},
		{
			86, NCONSTCAT_CONVERSATIONS,
			TEXT("FORCE_BREAKUP"), TEXT("FORCE_BREAKUP"), TEXT("FORCE_BREAKUP"),
			Value(ExtClass::ConversationId::FORCE_BREAKUP)
		},
		{
			87, NCONSTCAT_CONVERSATIONS,
			TEXT("REVEAL_PREGNANCY"), TEXT("REVEAL_PREGNANCY"), TEXT("REVEAL_PREGNANCY"),
			Value(ExtClass::ConversationId::REVEAL_PREGNANCY)
		},
		{
			88, NCONSTCAT_CONVERSATIONS,
			TEXT("I_WILL_CHEAT"), TEXT("I_WILL_CHEAT"), TEXT("I_WILL_CHEAT"),
			Value(ExtClass::ConversationId::I_WILL_CHEAT)
		},
		{
			89, NCONSTCAT_CONVERSATIONS,
				TEXT("EXPLOITABLE_LINE"), TEXT("EXPLOITABLE_LINE"), TEXT("EXPLOITABLE_LINE"),
				Value(90)
		},
		{
			90, NCONSTCAT_CONVERSATIONS,
			TEXT("STOP_FOLLOWING"), TEXT("STOP_FOLLOWING"), TEXT("STOP_FOLLOWING"),
			Value(ExtClass::ConversationId::STOP_FOLLOWING)
		},
		{
			91, NCONSTCAT_CONVERSATIONS,
			TEXT("MURDER_NOTICE"), TEXT("MURDER_NOTICE"), TEXT("MURDER_NOTICE"),
			Value(ExtClass::ConversationId::MURDER_NOTICE)
		},
		{
			92, NCONSTCAT_CONVERSATIONS,
			TEXT("SOMEONE_LIKES_YOU"), TEXT("SOMEONE_LIKES_YOU"), TEXT("SOMEONE_LIKES_YOU"),
			Value(ExtClass::ConversationId::SOMEONE_LIKES_YOU)
		},
		{
			93, NCONSTCAT_CONVERSATIONS,
			TEXT("SOMEONE_GOT_CONFESSED_TO"), TEXT("SOMEONE_GOT_CONFESSED_TO"), TEXT("SOMEONE_GOT_CONFESSED_TO"),
			Value(ExtClass::ConversationId::SOMEONE_GOT_CONFESSED_TO)
		},
		{
			94, NCONSTCAT_CONVERSATIONS,
			TEXT("I_SAW_SOMEONE_HAVE_H"), TEXT("I_SAW_SOMEONE_HAVE_H"), TEXT("I_SAW_SOMEONE_HAVE_H"),
			Value(ExtClass::ConversationId::I_SAW_SOMEONE_HAVE_H)
		},
		{
			95, NCONSTCAT_CONVERSATIONS,
			TEXT("STOP_FOLLOWING"), TEXT("STOP_FOLLOWING"), TEXT("STOP_FOLLOWING"),
			Value(ExtClass::ConversationId::STOP_FOLLOWING)
		},
		{
			96, NCONSTCAT_CONVERSATIONS,
			TEXT("DO_NOT_GET_INVOLVED"), TEXT("DO_NOT_GET_INVOLVED"), TEXT("DO_NOT_GET_INVOLVED"),
			Value(ExtClass::ConversationId::DO_NOT_GET_INVOLVED)
		},
		{
			97, NCONSTCAT_CONVERSATIONS,
			TEXT("SHAMELESS"), TEXT("SHAMELESS"), TEXT("SHAMELESS"),
			Value(ExtClass::ConversationId::SHAMELESS)
		},
		{
			98, NCONSTCAT_CONVERSATIONS,
				TEXT("NO_PROMPT_H"), TEXT("NO_PROMPT_H"), TEXT("NO_PROMPT_H"),
				Value(99)
		},
		{
			99, NCONSTCAT_CONVERSATIONS,
				TEXT("AFTER_H"), TEXT("AFTER_H"), TEXT("AFTER_H"),
				Value(101)
		},
		{
			100, NCONSTCAT_CONVERSATIONS,
			TEXT("FOLLOW_ME_H"), TEXT("FOLLOW_ME_H"), TEXT("FOLLOW_ME_H"),
			Value(ExtClass::ConversationId::FOLLOW_ME_H)
		},
		{
			101, NCONSTCAT_CONVERSATIONS,
			TEXT("DATE_GREETING"), TEXT("DATE_GREETING"), TEXT("DATE_GREETING"),
			Value(ExtClass::ConversationId::DATE_GREETING)
		},
		{
			102, NCONSTCAT_CONVERSATIONS,
			TEXT("CHANGE_CLOTHES"), TEXT("CHANGE_CLOTHES"), TEXT("CHANGE_CLOTHES"),
			Value(ExtClass::ConversationId::CHANGE_CLOTHES)
		},
		{
			103, NCONSTCAT_CONVERSATIONS,
			TEXT("DO_CLUB"), TEXT("DO_CLUB"), TEXT("DO_CLUB"),
			Value(ExtClass::ConversationId::DO_CLUB)
		},
		/*{
			104, NCONSTCAT_CONVERSATIONS,
			TEXT("TEST_3P"), TEXT("TEST_3P"), TEXT("TEST_3P"),
			Value(ExtClass::ConversationId::TEST_3P)
		},*/
		{
			105, NCONSTCAT_CONVERSATIONS,
			TEXT("MINNA_H"), TEXT("MINNA_H"), TEXT("MINNA_H"),
			Value(ExtClass::ConversationId::MINNA_H)
		},
		//Trait
		{
			106, NCONSTCAT_TRAIT,
			TEXT("EASYGOING"), TEXT("EASYGOING"), TEXT("EASYGOING"),
			Value(0)
		},
		{
			107, NCONSTCAT_TRAIT,
			TEXT("AFFABLE"), TEXT("AFFABLE"), TEXT("AFFABLE"),
			Value(1)
		},
		{
			108, NCONSTCAT_TRAIT,
			TEXT("BAD_WITH_GUYS"), TEXT("BAD_WITH_GUYS"), TEXT("BAD_WITH_GUYS"),
			Value(2)
		},
		{
			109, NCONSTCAT_TRAIT,
			TEXT("BAD_WITH_GIRLS"), TEXT("BAD_WITH_GIRLS"), TEXT("BAD_WITH_GIRLS"),
			Value(3)
		},
		{
			110, NCONSTCAT_TRAIT,
			TEXT("CHARMING"), TEXT("CHARMING"), TEXT("CHARMING"),
			Value(4)
		},
		{
			111, NCONSTCAT_TRAIT,
			TEXT("TSUNDERE"), TEXT("TSUNDERE"), TEXT("TSUNDERE"),
			Value(5)
		},
		{
			112, NCONSTCAT_TRAIT,
			TEXT("CHIVALROUS"), TEXT("CHIVALROUS"), TEXT("CHIVALROUS"),
			Value(6)
		},
		{
			113, NCONSTCAT_TRAIT,
			TEXT("TRENDY"), TEXT("TRENDY"), TEXT("TRENDY"),
			Value(7)
		},
		{
			114, NCONSTCAT_TRAIT,
			TEXT("OBEDIENT"), TEXT("OBEDIENT"), TEXT("OBEDIENT"),
			Value(8)
		},
		{
			115, NCONSTCAT_TRAIT,
			TEXT("POSITIVE"), TEXT("POSITIVE"), TEXT("POSITIVE"),
			Value(9)
		},
		{
			116, NCONSTCAT_TRAIT,
			TEXT("SHY"), TEXT("SHY"), TEXT("SHY"),
			Value(10)
		},
		{
			117, NCONSTCAT_TRAIT,
			TEXT("JEALOUS"), TEXT("JEALOUS"), TEXT("JEALOUS"),
			Value(11)
		},
		{
			118, NCONSTCAT_TRAIT,
			TEXT("MELANCHOLY"), TEXT("MELANCHOLY"), TEXT("MELANCHOLY"),
			Value(12)
		},
		{
			119, NCONSTCAT_TRAIT,
			TEXT("PERVERTED"), TEXT("PERVERTED"), TEXT("PERVERTED"),
			Value(13)
		},
		{
			120, NCONSTCAT_TRAIT,
			TEXT("SERIOUS"), TEXT("SERIOUS"), TEXT("SERIOUS"),
			Value(14)
		},
		{
			121, NCONSTCAT_TRAIT,
			TEXT("CALM"), TEXT("CALM"), TEXT("CALM"),
			Value(15)
		},
		{
			122, NCONSTCAT_TRAIT,
			TEXT("IMPULSIVE"), TEXT("IMPULSIVE"), TEXT("IMPULSIVE"),
			Value(16)
		},
		{
			123, NCONSTCAT_TRAIT,
			TEXT("ABSENTMINDED"), TEXT("ABSENTMINDED"), TEXT("ABSENTMINDED"),
			Value(17)
		},
		{
			124, NCONSTCAT_TRAIT,
			TEXT("VIOLENT"), TEXT("VIOLENT"), TEXT("VIOLENT"),
			Value(18)
		},
		{
			125, NCONSTCAT_TRAIT,
			TEXT("PASSIVE"), TEXT("PASSIVE"), TEXT("PASSIVE"),
			Value(19)
		},
		{
			126, NCONSTCAT_TRAIT,
			TEXT("MEDDLESOME"), TEXT("MEDDLESOME"), TEXT("MEDDLESOME"),
			Value(20)
		},
		{
			127, NCONSTCAT_TRAIT,
			TEXT("CLASS_PREZ"), TEXT("CLASS_PREZ"), TEXT("CLASS_PREZ"),
			Value(21)
		},
		{
			128, NCONSTCAT_TRAIT,
			TEXT("CHATTY"), TEXT("CHATTY"), TEXT("CHATTY"),
			Value(22)
		},
		{
			129, NCONSTCAT_TRAIT,
			TEXT("ALWAYS_HUNGRY"), TEXT("ALWAYS_HUNGRY"), TEXT("ALWAYS_HUNGRY"),
			Value(23)
		},
		{
			130, NCONSTCAT_TRAIT,
			TEXT("ROMANTIC"), TEXT("ROMANTIC"), TEXT("ROMANTIC"),
			Value(24)
		},
		{
			131, NCONSTCAT_TRAIT,
			TEXT("SINGLEMINDED"), TEXT("SINGLEMINDED"), TEXT("SINGLEMINDED"),
			Value(25)
		},
		{
			132, NCONSTCAT_TRAIT,
			TEXT("INDECISIVE"), TEXT("INDECISIVE"), TEXT("INDECISIVE"),
			Value(26)
		},
		{
			133, NCONSTCAT_TRAIT,
			TEXT("COMPETITIVE"), TEXT("COMPETITIVE"), TEXT("COMPETITIVE"),
			Value(27)
		},
		{
			134, NCONSTCAT_TRAIT,
			TEXT("SCHEMING"), TEXT("SCHEMING"), TEXT("SCHEMING"),
			Value(28)
		},
		{
			135, NCONSTCAT_TRAIT,
			TEXT("DILIGENT"), TEXT("DILIGENT"), TEXT("DILIGENT"),
			Value(29)
		},
		{
			136, NCONSTCAT_TRAIT,
			TEXT("WILD"), TEXT("WILD"), TEXT("WILD"),
			Value(30)
		},
		{
			137, NCONSTCAT_TRAIT,
			TEXT("MASOCHIST"), TEXT("MASOCHIST"), TEXT("MASOCHIST"),
			Value(31)
		},
		{
			138, NCONSTCAT_TRAIT,
			TEXT("SWEATY"), TEXT("SWEATY"), TEXT("SWEATY"),
			Value(32)
		},
		{
			139, NCONSTCAT_TRAIT,
			TEXT("EVIL"), TEXT("EVIL"), TEXT("EVIL"),
			Value(33)
		},
		{
			140, NCONSTCAT_TRAIT,
			TEXT("DEAF"), TEXT("DEAF"), TEXT("DEAF"),
			Value(34)
		},
		{
			141, NCONSTCAT_TRAIT,
			TEXT("EXPLOITABLE"), TEXT("EXPLOITABLE"), TEXT("EXPLOITABLE"),
			Value(35)
		},
		{
			142, NCONSTCAT_TRAIT,
			TEXT("ASEXUAL"), TEXT("ASEXUAL"), TEXT("ASEXUAL"),
			Value(36)
		},
		{
			143, NCONSTCAT_TRAIT,
			TEXT("LUCKY"), TEXT("LUCKY"), TEXT("LUCKY"),
			Value(37)
		},
		{
			144, NCONSTCAT_TRAIT,
			TEXT("RAINBOW"), TEXT("RAINBOW"), TEXT("RAINBOW"),
			Value(38)
		},
	},
	{ //BOOL
		
	},
	{ //FLOAT
		
	},
	{ //STRING
		
	}

};






}
}